modLoader="javafml"
loaderVersion="[47,)"
license="GNU General Public License version 3 (GPLv3)"

[[mods]]
modId="farout"
version="0.12"
displayName="Farout"
displayURL="https://www.curseforge.com/minecraft/mc-mods/far-out"
logoFile="logo.png"
credits="Made By BetaStar9108."
authors="BetaStar9108"
description="A space exploration mod set in a globular cluster."

[[dependencies.farout]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"

[[dependencies.farout]]
    modId="forge"
    mandatory=true
    versionRange="[47.2.0]"
    ordering="NONE"
    side="BOTH"


[[dependencies.farout]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

