
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.far_out.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.client.event.RegisterColorHandlersEvent;
import net.minecraftforge.api.distmarker.Dist;

import net.minecraft.world.level.block.Block;

import net.mcreator.far_out.block.ZirconOreBlock;
import net.mcreator.far_out.block.ZPinchFusionReactorBlock;
import net.mcreator.far_out.block.YellowTorcherBlock;
import net.mcreator.far_out.block.UranistoneBlock;
import net.mcreator.far_out.block.UnactivatedLampBlock;
import net.mcreator.far_out.block.TokamakfusionreactorBlock;
import net.mcreator.far_out.block.SupercooledIceBlock;
import net.mcreator.far_out.block.SulfuricAcidBlock;
import net.mcreator.far_out.block.SulfurBlockBlock;
import net.mcreator.far_out.block.SubspaceCatalystBlock;
import net.mcreator.far_out.block.StralakiteBlock;
import net.mcreator.far_out.block.StirlingEngineBlock;
import net.mcreator.far_out.block.SteamGeneratorBlock;
import net.mcreator.far_out.block.SpodumeneOreBlock;
import net.mcreator.far_out.block.SolarVinesCapBlock;
import net.mcreator.far_out.block.SolarVinesBlock;
import net.mcreator.far_out.block.SolarPanelsBlock;
import net.mcreator.far_out.block.SandosArenaPortalBlock;
import net.mcreator.far_out.block.SaltwaterBlock;
import net.mcreator.far_out.block.SaltBlockBlock;
import net.mcreator.far_out.block.RustBlock;
import net.mcreator.far_out.block.RocketAssemblyManagerBlock;
import net.mcreator.far_out.block.RocketAssemblerBlock;
import net.mcreator.far_out.block.RoadSpawnerBlock;
import net.mcreator.far_out.block.RedTorcherBlock;
import net.mcreator.far_out.block.RedAlgaeBlock;
import net.mcreator.far_out.block.RadioisotopeThermoelectricGeneratorBlock;
import net.mcreator.far_out.block.ROMProgrammerBlock;
import net.mcreator.far_out.block.QuzanWoodBlock;
import net.mcreator.far_out.block.QuzanStairsBlock;
import net.mcreator.far_out.block.QuzanSlabBlock;
import net.mcreator.far_out.block.QuzanPressurePlateBlock;
import net.mcreator.far_out.block.QuzanPlanksBlock;
import net.mcreator.far_out.block.QuzanLogBlock;
import net.mcreator.far_out.block.QuzanLeavesBlock;
import net.mcreator.far_out.block.QuzanFenceGateBlock;
import net.mcreator.far_out.block.QuzanFenceBlock;
import net.mcreator.far_out.block.QuzanDoorBlock;
import net.mcreator.far_out.block.QuzanButtonBlock;
import net.mcreator.far_out.block.QuartzOreBlock;
import net.mcreator.far_out.block.PyriteBlock;
import net.mcreator.far_out.block.PurplegrassBlock;
import net.mcreator.far_out.block.PlutoniumFuelRodBundleBlock;
import net.mcreator.far_out.block.OxyfionWoodBlock;
import net.mcreator.far_out.block.OxyfionStairsBlock;
import net.mcreator.far_out.block.OxyfionSlabBlock;
import net.mcreator.far_out.block.OxyfionPressurePlateBlock;
import net.mcreator.far_out.block.OxyfionPlanksBlock;
import net.mcreator.far_out.block.OxyfionLogBlock;
import net.mcreator.far_out.block.OxyfionLeavesBlock;
import net.mcreator.far_out.block.OxyfionFenceGateBlock;
import net.mcreator.far_out.block.OxyfionFenceBlock;
import net.mcreator.far_out.block.OxyfionButtonBlock;
import net.mcreator.far_out.block.NuclearReactorBlock;
import net.mcreator.far_out.block.MusniusWoodBlock;
import net.mcreator.far_out.block.MusniusTreeTrunkBlock;
import net.mcreator.far_out.block.MusniusStairsBlock;
import net.mcreator.far_out.block.MusniusSlabBlock;
import net.mcreator.far_out.block.MusniusSaplingBlock;
import net.mcreator.far_out.block.MusniusPressurePlateBlock;
import net.mcreator.far_out.block.MusniusPlanksBlock;
import net.mcreator.far_out.block.MusniusLeavesBlock;
import net.mcreator.far_out.block.MusniusFenceGateBlock;
import net.mcreator.far_out.block.MusniusFenceBlock;
import net.mcreator.far_out.block.MusniusButtonBlock;
import net.mcreator.far_out.block.MethanePolymerizerBlock;
import net.mcreator.far_out.block.MatterAntimatterCompressorBlock;
import net.mcreator.far_out.block.MagmaBlock;
import net.mcreator.far_out.block.LumiblossomWoodBlock;
import net.mcreator.far_out.block.LumiblossomStairsBlock;
import net.mcreator.far_out.block.LumiblossomSlabBlock;
import net.mcreator.far_out.block.LumiblossomPressurePlateBlock;
import net.mcreator.far_out.block.LumiblossomPlanksBlock;
import net.mcreator.far_out.block.LumiblossomLogBlock;
import net.mcreator.far_out.block.LumiblossomLeavesBlock;
import net.mcreator.far_out.block.LumiblossomFenceGateBlock;
import net.mcreator.far_out.block.LumiblossomFenceBlock;
import net.mcreator.far_out.block.LumiblossomButtonBlock;
import net.mcreator.far_out.block.LonsdaleiteOreBlock;
import net.mcreator.far_out.block.LonsdaleiteBlockBlock;
import net.mcreator.far_out.block.LiquidSulfurDioxideBlock;
import net.mcreator.far_out.block.LiquidMethaneBlock;
import net.mcreator.far_out.block.LiquidAmmoniaBlock;
import net.mcreator.far_out.block.LightWaterModerationTanksBlock;
import net.mcreator.far_out.block.LaunchpadTilesBlock;
import net.mcreator.far_out.block.KeranonWoodBlock;
import net.mcreator.far_out.block.KeranonStairsBlock;
import net.mcreator.far_out.block.KeranonSlabBlock;
import net.mcreator.far_out.block.KeranonPressurePlateBlock;
import net.mcreator.far_out.block.KeranonPlanksBlock;
import net.mcreator.far_out.block.KeranonLogBlock;
import net.mcreator.far_out.block.KeranonLeavesBlock;
import net.mcreator.far_out.block.KeranonFenceGateBlock;
import net.mcreator.far_out.block.KeranonFenceBlock;
import net.mcreator.far_out.block.KeranonButtonBlock;
import net.mcreator.far_out.block.KempatWoodBlock;
import net.mcreator.far_out.block.KempatStairsBlock;
import net.mcreator.far_out.block.KempatSlabBlock;
import net.mcreator.far_out.block.KempatSaplingBlock;
import net.mcreator.far_out.block.KempatPressurePlateBlock;
import net.mcreator.far_out.block.KempatPlanksBlock;
import net.mcreator.far_out.block.KempatLogBlock;
import net.mcreator.far_out.block.KempatLeavesBlock;
import net.mcreator.far_out.block.KempatFenceGateBlock;
import net.mcreator.far_out.block.KempatFenceBlock;
import net.mcreator.far_out.block.KempatButtonBlock;
import net.mcreator.far_out.block.IronPentacarbonylBlock;
import net.mcreator.far_out.block.IntegratedCircuitFabricatorBlock;
import net.mcreator.far_out.block.ImmatureEtauosianGrainstalkBlock;
import net.mcreator.far_out.block.HyperstableAlloyStairsBlock;
import net.mcreator.far_out.block.HyperstableAlloyBlock;
import net.mcreator.far_out.block.HydrogenSulfideBlock;
import net.mcreator.far_out.block.HydrogenFuelCellBlock;
import net.mcreator.far_out.block.HeatPipeBlock;
import net.mcreator.far_out.block.HeatPipeBentBlock;
import net.mcreator.far_out.block.GreenOilBlock;
import net.mcreator.far_out.block.GraphiteRodAssemblyUraniumBlock;
import net.mcreator.far_out.block.GraphiteRodAssemblyPlutoniumBlock;
import net.mcreator.far_out.block.GraphiteRodAssemblyBlock;
import net.mcreator.far_out.block.GraphiteOreBlock;
import net.mcreator.far_out.block.EtauosianGrainstalkBlock;
import net.mcreator.far_out.block.ElectrolyzerBlock;
import net.mcreator.far_out.block.DesktopComputerBlock;
import net.mcreator.far_out.block.DesigningWorkbenchBlock;
import net.mcreator.far_out.block.CrystalineExoskeletonBlock;
import net.mcreator.far_out.block.CrushedQuartzBlock;
import net.mcreator.far_out.block.CrudeSeebeckGeneratorBlock;
import net.mcreator.far_out.block.CopperCableBlock;
import net.mcreator.far_out.block.ConstratiumOreBlock;
import net.mcreator.far_out.block.ConstratiumBlockBlock;
import net.mcreator.far_out.block.CoffiniteOreBlock;
import net.mcreator.far_out.block.CoalGasificationReactorBlock;
import net.mcreator.far_out.block.ChlorinatedEarthBlock;
import net.mcreator.far_out.block.ChlorellaCultureBlock;
import net.mcreator.far_out.block.ChemosyntheticNodulesBlock;
import net.mcreator.far_out.block.ChemistryWorkbenchBlock;
import net.mcreator.far_out.block.ChacoavinesBlock;
import net.mcreator.far_out.block.ChacoaBlock;
import net.mcreator.far_out.block.CargoPodBlock;
import net.mcreator.far_out.block.CardboardboxBlock;
import net.mcreator.far_out.block.BreathableAirBlock;
import net.mcreator.far_out.block.BoraxOreBlock;
import net.mcreator.far_out.block.BlueTorcherBlock;
import net.mcreator.far_out.block.BioPlasticWindowBlock;
import net.mcreator.far_out.block.BauxiteBlock;
import net.mcreator.far_out.block.BasalticDirtBlock;
import net.mcreator.far_out.block.AtmosphericLiquidfierBlock;
import net.mcreator.far_out.block.AsphaltBlock;
import net.mcreator.far_out.block.AqueousAmmoniaBlock;
import net.mcreator.far_out.block.ApartmentSpawnerBlock;
import net.mcreator.far_out.block.AncientSedimentBlock;
import net.mcreator.far_out.block.AmmoniciteBlock;
import net.mcreator.far_out.block.AlienReedsBlock;
import net.mcreator.far_out.block.AirtightHabitatWallBlock;
import net.mcreator.far_out.block.ActivatedLampBlock;
import net.mcreator.far_out.FaroutMod;

public class FaroutModBlocks {
	public static final DeferredRegister<Block> REGISTRY = DeferredRegister.create(ForgeRegistries.BLOCKS, FaroutMod.MODID);
	public static final RegistryObject<Block> TOKAMAKFUSIONREACTOR = REGISTRY.register("tokamakfusionreactor", () -> new TokamakfusionreactorBlock());
	public static final RegistryObject<Block> CARDBOARDBOX = REGISTRY.register("cardboardbox", () -> new CardboardboxBlock());
	public static final RegistryObject<Block> CHACOA = REGISTRY.register("chacoa", () -> new ChacoaBlock());
	public static final RegistryObject<Block> CHACOAVINES = REGISTRY.register("chacoavines", () -> new ChacoavinesBlock());
	public static final RegistryObject<Block> DESKTOP_COMPUTER = REGISTRY.register("desktop_computer", () -> new DesktopComputerBlock());
	public static final RegistryObject<Block> GRAPHITE_ORE = REGISTRY.register("graphite_ore", () -> new GraphiteOreBlock());
	public static final RegistryObject<Block> ELECTROLYZER = REGISTRY.register("electrolyzer", () -> new ElectrolyzerBlock());
	public static final RegistryObject<Block> SALTWATER = REGISTRY.register("saltwater", () -> new SaltwaterBlock());
	public static final RegistryObject<Block> ALIEN_REEDS = REGISTRY.register("alien_reeds", () -> new AlienReedsBlock());
	public static final RegistryObject<Block> BIO_PLASTIC_WINDOW = REGISTRY.register("bio_plastic_window", () -> new BioPlasticWindowBlock());
	public static final RegistryObject<Block> INTEGRATED_CIRCUIT_FABRICATOR = REGISTRY.register("integrated_circuit_fabricator", () -> new IntegratedCircuitFabricatorBlock());
	public static final RegistryObject<Block> BAUXITE = REGISTRY.register("bauxite", () -> new BauxiteBlock());
	public static final RegistryObject<Block> SULFURIC_ACID = REGISTRY.register("sulfuric_acid", () -> new SulfuricAcidBlock());
	public static final RegistryObject<Block> CHEMOSYNTHETIC_NODULES = REGISTRY.register("chemosynthetic_nodules", () -> new ChemosyntheticNodulesBlock());
	public static final RegistryObject<Block> CRYSTALINE_EXOSKELETON = REGISTRY.register("crystaline_exoskeleton", () -> new CrystalineExoskeletonBlock());
	public static final RegistryObject<Block> GREEN_OIL = REGISTRY.register("green_oil", () -> new GreenOilBlock());
	public static final RegistryObject<Block> ASPHALT = REGISTRY.register("asphalt", () -> new AsphaltBlock());
	public static final RegistryObject<Block> LIQUID_AMMONIA = REGISTRY.register("liquid_ammonia", () -> new LiquidAmmoniaBlock());
	public static final RegistryObject<Block> CARGO_POD = REGISTRY.register("cargo_pod", () -> new CargoPodBlock());
	public static final RegistryObject<Block> AIRTIGHT_HABITAT_WALL = REGISTRY.register("airtight_habitat_wall", () -> new AirtightHabitatWallBlock());
	public static final RegistryObject<Block> Z_PINCH_FUSION_REACTOR = REGISTRY.register("z_pinch_fusion_reactor", () -> new ZPinchFusionReactorBlock());
	public static final RegistryObject<Block> COFFINITE_ORE = REGISTRY.register("coffinite_ore", () -> new CoffiniteOreBlock());
	public static final RegistryObject<Block> SPODUMENE_ORE = REGISTRY.register("spodumene_ore", () -> new SpodumeneOreBlock());
	public static final RegistryObject<Block> LUMIBLOSSOM_WOOD = REGISTRY.register("lumiblossom_wood", () -> new LumiblossomWoodBlock());
	public static final RegistryObject<Block> LUMIBLOSSOM_LOG = REGISTRY.register("lumiblossom_log", () -> new LumiblossomLogBlock());
	public static final RegistryObject<Block> LUMIBLOSSOM_PLANKS = REGISTRY.register("lumiblossom_planks", () -> new LumiblossomPlanksBlock());
	public static final RegistryObject<Block> LUMIBLOSSOM_STAIRS = REGISTRY.register("lumiblossom_stairs", () -> new LumiblossomStairsBlock());
	public static final RegistryObject<Block> LUMIBLOSSOM_SLAB = REGISTRY.register("lumiblossom_slab", () -> new LumiblossomSlabBlock());
	public static final RegistryObject<Block> LUMIBLOSSOM_FENCE = REGISTRY.register("lumiblossom_fence", () -> new LumiblossomFenceBlock());
	public static final RegistryObject<Block> LUMIBLOSSOM_FENCE_GATE = REGISTRY.register("lumiblossom_fence_gate", () -> new LumiblossomFenceGateBlock());
	public static final RegistryObject<Block> LUMIBLOSSOM_PRESSURE_PLATE = REGISTRY.register("lumiblossom_pressure_plate", () -> new LumiblossomPressurePlateBlock());
	public static final RegistryObject<Block> LUMIBLOSSOM_BUTTON = REGISTRY.register("lumiblossom_button", () -> new LumiblossomButtonBlock());
	public static final RegistryObject<Block> QUARTZ_ORE = REGISTRY.register("quartz_ore", () -> new QuartzOreBlock());
	public static final RegistryObject<Block> SOLAR_VINES_CAP = REGISTRY.register("solar_vines_cap", () -> new SolarVinesCapBlock());
	public static final RegistryObject<Block> SOLAR_VINES = REGISTRY.register("solar_vines", () -> new SolarVinesBlock());
	public static final RegistryObject<Block> RED_TORCHER = REGISTRY.register("red_torcher", () -> new RedTorcherBlock());
	public static final RegistryObject<Block> YELLOW_TORCHER = REGISTRY.register("yellow_torcher", () -> new YellowTorcherBlock());
	public static final RegistryObject<Block> BLUE_TORCHER = REGISTRY.register("blue_torcher", () -> new BlueTorcherBlock());
	public static final RegistryObject<Block> CHLORELLA_CULTURE = REGISTRY.register("chlorella_culture", () -> new ChlorellaCultureBlock());
	public static final RegistryObject<Block> ANCIENT_SEDIMENT = REGISTRY.register("ancient_sediment", () -> new AncientSedimentBlock());
	public static final RegistryObject<Block> SALT_BLOCK = REGISTRY.register("salt_block", () -> new SaltBlockBlock());
	public static final RegistryObject<Block> LIQUID_SULFUR_DIOXIDE = REGISTRY.register("liquid_sulfur_dioxide", () -> new LiquidSulfurDioxideBlock());
	public static final RegistryObject<Block> LUMIBLOSSOM_LEAVES = REGISTRY.register("lumiblossom_leaves", () -> new LumiblossomLeavesBlock());
	public static final RegistryObject<Block> RUST = REGISTRY.register("rust", () -> new RustBlock());
	public static final RegistryObject<Block> CRUSHED_QUARTZ = REGISTRY.register("crushed_quartz", () -> new CrushedQuartzBlock());
	public static final RegistryObject<Block> AQUEOUS_AMMONIA = REGISTRY.register("aqueous_ammonia", () -> new AqueousAmmoniaBlock());
	public static final RegistryObject<Block> HYDROGEN_FUEL_CELL = REGISTRY.register("hydrogen_fuel_cell", () -> new HydrogenFuelCellBlock());
	public static final RegistryObject<Block> BASALTIC_DIRT = REGISTRY.register("basaltic_dirt", () -> new BasalticDirtBlock());
	public static final RegistryObject<Block> ETAUOSIAN_GRAINSTALK = REGISTRY.register("etauosian_grainstalk", () -> new EtauosianGrainstalkBlock());
	public static final RegistryObject<Block> STIRLING_ENGINE = REGISTRY.register("stirling_engine", () -> new StirlingEngineBlock());
	public static final RegistryObject<Block> IMMATURE_ETAUOSIAN_GRAINSTALK = REGISTRY.register("immature_etauosian_grainstalk", () -> new ImmatureEtauosianGrainstalkBlock());
	public static final RegistryObject<Block> MUSNIUS_TREE_TRUNK = REGISTRY.register("musnius_tree_trunk", () -> new MusniusTreeTrunkBlock());
	public static final RegistryObject<Block> MUSNIUS_WOOD = REGISTRY.register("musnius_wood", () -> new MusniusWoodBlock());
	public static final RegistryObject<Block> MUSNIUS_STAIRS = REGISTRY.register("musnius_stairs", () -> new MusniusStairsBlock());
	public static final RegistryObject<Block> MUSNIUS_SLAB = REGISTRY.register("musnius_slab", () -> new MusniusSlabBlock());
	public static final RegistryObject<Block> MUSNIUS_FENCE = REGISTRY.register("musnius_fence", () -> new MusniusFenceBlock());
	public static final RegistryObject<Block> MUSNIUS_FENCE_GATE = REGISTRY.register("musnius_fence_gate", () -> new MusniusFenceGateBlock());
	public static final RegistryObject<Block> MUSNIUS_PRESSURE_PLATE = REGISTRY.register("musnius_pressure_plate", () -> new MusniusPressurePlateBlock());
	public static final RegistryObject<Block> MUSNIUS_BUTTON = REGISTRY.register("musnius_button", () -> new MusniusButtonBlock());
	public static final RegistryObject<Block> MUSNIUS_PLANKS = REGISTRY.register("musnius_planks", () -> new MusniusPlanksBlock());
	public static final RegistryObject<Block> MUSNIUS_LEAVES = REGISTRY.register("musnius_leaves", () -> new MusniusLeavesBlock());
	public static final RegistryObject<Block> MUSNIUS_SAPLING = REGISTRY.register("musnius_sapling", () -> new MusniusSaplingBlock());
	public static final RegistryObject<Block> DESIGNING_WORKBENCH = REGISTRY.register("designing_workbench", () -> new DesigningWorkbenchBlock());
	public static final RegistryObject<Block> LAUNCHPAD_TILES = REGISTRY.register("launchpad_tiles", () -> new LaunchpadTilesBlock());
	public static final RegistryObject<Block> ROCKET_ASSEMBLY_MANAGER = REGISTRY.register("rocket_assembly_manager", () -> new RocketAssemblyManagerBlock());
	public static final RegistryObject<Block> ROCKET_ASSEMBLER = REGISTRY.register("rocket_assembler", () -> new RocketAssemblerBlock());
	public static final RegistryObject<Block> LIQUID_METHANE = REGISTRY.register("liquid_methane", () -> new LiquidMethaneBlock());
	public static final RegistryObject<Block> STRALAKITE = REGISTRY.register("stralakite", () -> new StralakiteBlock());
	public static final RegistryObject<Block> COAL_GASIFICATION_REACTOR = REGISTRY.register("coal_gasification_reactor", () -> new CoalGasificationReactorBlock());
	public static final RegistryObject<Block> SOLAR_PANELS = REGISTRY.register("solar_panels", () -> new SolarPanelsBlock());
	public static final RegistryObject<Block> KEMPAT_WOOD = REGISTRY.register("kempat_wood", () -> new KempatWoodBlock());
	public static final RegistryObject<Block> KEMPAT_LOG = REGISTRY.register("kempat_log", () -> new KempatLogBlock());
	public static final RegistryObject<Block> KEMPAT_PLANKS = REGISTRY.register("kempat_planks", () -> new KempatPlanksBlock());
	public static final RegistryObject<Block> KEMPAT_LEAVES = REGISTRY.register("kempat_leaves", () -> new KempatLeavesBlock());
	public static final RegistryObject<Block> KEMPAT_STAIRS = REGISTRY.register("kempat_stairs", () -> new KempatStairsBlock());
	public static final RegistryObject<Block> KEMPAT_SLAB = REGISTRY.register("kempat_slab", () -> new KempatSlabBlock());
	public static final RegistryObject<Block> KEMPAT_FENCE = REGISTRY.register("kempat_fence", () -> new KempatFenceBlock());
	public static final RegistryObject<Block> KEMPAT_FENCE_GATE = REGISTRY.register("kempat_fence_gate", () -> new KempatFenceGateBlock());
	public static final RegistryObject<Block> KEMPAT_PRESSURE_PLATE = REGISTRY.register("kempat_pressure_plate", () -> new KempatPressurePlateBlock());
	public static final RegistryObject<Block> KEMPAT_BUTTON = REGISTRY.register("kempat_button", () -> new KempatButtonBlock());
	public static final RegistryObject<Block> GRAPHITE_ROD_ASSEMBLY = REGISTRY.register("graphite_rod_assembly", () -> new GraphiteRodAssemblyBlock());
	public static final RegistryObject<Block> CHLORINATED_EARTH = REGISTRY.register("chlorinated_earth", () -> new ChlorinatedEarthBlock());
	public static final RegistryObject<Block> BORAX_ORE = REGISTRY.register("borax_ore", () -> new BoraxOreBlock());
	public static final RegistryObject<Block> UNACTIVATED_LAMP = REGISTRY.register("unactivated_lamp", () -> new UnactivatedLampBlock());
	public static final RegistryObject<Block> PYRITE = REGISTRY.register("pyrite", () -> new PyriteBlock());
	public static final RegistryObject<Block> SANDOS_ARENA_PORTAL = REGISTRY.register("sandos_arena_portal", () -> new SandosArenaPortalBlock());
	public static final RegistryObject<Block> GRAPHITE_ROD_ASSEMBLY_PLUTONIUM = REGISTRY.register("graphite_rod_assembly_plutonium", () -> new GraphiteRodAssemblyPlutoniumBlock());
	public static final RegistryObject<Block> GRAPHITE_ROD_ASSEMBLY_URANIUM = REGISTRY.register("graphite_rod_assembly_uranium", () -> new GraphiteRodAssemblyUraniumBlock());
	public static final RegistryObject<Block> ZIRCON_ORE = REGISTRY.register("zircon_ore", () -> new ZirconOreBlock());
	public static final RegistryObject<Block> PURPLEGRASS = REGISTRY.register("purplegrass", () -> new PurplegrassBlock());
	public static final RegistryObject<Block> SUBSPACE_CATALYST = REGISTRY.register("subspace_catalyst", () -> new SubspaceCatalystBlock());
	public static final RegistryObject<Block> METHANE_POLYMERIZER = REGISTRY.register("methane_polymerizer", () -> new MethanePolymerizerBlock());
	public static final RegistryObject<Block> QUZAN_WOOD = REGISTRY.register("quzan_wood", () -> new QuzanWoodBlock());
	public static final RegistryObject<Block> QUZAN_LOG = REGISTRY.register("quzan_log", () -> new QuzanLogBlock());
	public static final RegistryObject<Block> QUZAN_PLANKS = REGISTRY.register("quzan_planks", () -> new QuzanPlanksBlock());
	public static final RegistryObject<Block> QUZAN_LEAVES = REGISTRY.register("quzan_leaves", () -> new QuzanLeavesBlock());
	public static final RegistryObject<Block> QUZAN_STAIRS = REGISTRY.register("quzan_stairs", () -> new QuzanStairsBlock());
	public static final RegistryObject<Block> QUZAN_SLAB = REGISTRY.register("quzan_slab", () -> new QuzanSlabBlock());
	public static final RegistryObject<Block> QUZAN_FENCE = REGISTRY.register("quzan_fence", () -> new QuzanFenceBlock());
	public static final RegistryObject<Block> QUZAN_FENCE_GATE = REGISTRY.register("quzan_fence_gate", () -> new QuzanFenceGateBlock());
	public static final RegistryObject<Block> QUZAN_PRESSURE_PLATE = REGISTRY.register("quzan_pressure_plate", () -> new QuzanPressurePlateBlock());
	public static final RegistryObject<Block> QUZAN_BUTTON = REGISTRY.register("quzan_button", () -> new QuzanButtonBlock());
	public static final RegistryObject<Block> LONSDALEITE_ORE = REGISTRY.register("lonsdaleite_ore", () -> new LonsdaleiteOreBlock());
	public static final RegistryObject<Block> LONSDALEITE_BLOCK = REGISTRY.register("lonsdaleite_block", () -> new LonsdaleiteBlockBlock());
	public static final RegistryObject<Block> NUCLEAR_REACTOR = REGISTRY.register("nuclear_reactor", () -> new NuclearReactorBlock());
	public static final RegistryObject<Block> KEMPAT_SAPLING = REGISTRY.register("kempat_sapling", () -> new KempatSaplingBlock());
	public static final RegistryObject<Block> OXYFION_WOOD = REGISTRY.register("oxyfion_wood", () -> new OxyfionWoodBlock());
	public static final RegistryObject<Block> OXYFION_LOG = REGISTRY.register("oxyfion_log", () -> new OxyfionLogBlock());
	public static final RegistryObject<Block> OXYFION_PLANKS = REGISTRY.register("oxyfion_planks", () -> new OxyfionPlanksBlock());
	public static final RegistryObject<Block> OXYFION_LEAVES = REGISTRY.register("oxyfion_leaves", () -> new OxyfionLeavesBlock());
	public static final RegistryObject<Block> OXYFION_STAIRS = REGISTRY.register("oxyfion_stairs", () -> new OxyfionStairsBlock());
	public static final RegistryObject<Block> OXYFION_SLAB = REGISTRY.register("oxyfion_slab", () -> new OxyfionSlabBlock());
	public static final RegistryObject<Block> OXYFION_FENCE = REGISTRY.register("oxyfion_fence", () -> new OxyfionFenceBlock());
	public static final RegistryObject<Block> OXYFION_FENCE_GATE = REGISTRY.register("oxyfion_fence_gate", () -> new OxyfionFenceGateBlock());
	public static final RegistryObject<Block> OXYFION_PRESSURE_PLATE = REGISTRY.register("oxyfion_pressure_plate", () -> new OxyfionPressurePlateBlock());
	public static final RegistryObject<Block> OXYFION_BUTTON = REGISTRY.register("oxyfion_button", () -> new OxyfionButtonBlock());
	public static final RegistryObject<Block> IRON_PENTACARBONYL = REGISTRY.register("iron_pentacarbonyl", () -> new IronPentacarbonylBlock());
	public static final RegistryObject<Block> URANISTONE = REGISTRY.register("uranistone", () -> new UranistoneBlock());
	public static final RegistryObject<Block> MAGMA = REGISTRY.register("magma", () -> new MagmaBlock());
	public static final RegistryObject<Block> KERANON_WOOD = REGISTRY.register("keranon_wood", () -> new KeranonWoodBlock());
	public static final RegistryObject<Block> KERANON_LOG = REGISTRY.register("keranon_log", () -> new KeranonLogBlock());
	public static final RegistryObject<Block> KERANON_PLANKS = REGISTRY.register("keranon_planks", () -> new KeranonPlanksBlock());
	public static final RegistryObject<Block> KERANON_LEAVES = REGISTRY.register("keranon_leaves", () -> new KeranonLeavesBlock());
	public static final RegistryObject<Block> KERANON_STAIRS = REGISTRY.register("keranon_stairs", () -> new KeranonStairsBlock());
	public static final RegistryObject<Block> KERANON_SLAB = REGISTRY.register("keranon_slab", () -> new KeranonSlabBlock());
	public static final RegistryObject<Block> KERANON_FENCE = REGISTRY.register("keranon_fence", () -> new KeranonFenceBlock());
	public static final RegistryObject<Block> KERANON_FENCE_GATE = REGISTRY.register("keranon_fence_gate", () -> new KeranonFenceGateBlock());
	public static final RegistryObject<Block> KERANON_PRESSURE_PLATE = REGISTRY.register("keranon_pressure_plate", () -> new KeranonPressurePlateBlock());
	public static final RegistryObject<Block> KERANON_BUTTON = REGISTRY.register("keranon_button", () -> new KeranonButtonBlock());
	public static final RegistryObject<Block> HYPERSTABLE_ALLOY = REGISTRY.register("hyperstable_alloy", () -> new HyperstableAlloyBlock());
	public static final RegistryObject<Block> HYPERSTABLE_ALLOY_STAIRS = REGISTRY.register("hyperstable_alloy_stairs", () -> new HyperstableAlloyStairsBlock());
	public static final RegistryObject<Block> RED_ALGAE = REGISTRY.register("red_algae", () -> new RedAlgaeBlock());
	public static final RegistryObject<Block> CONSTRATIUM_ORE = REGISTRY.register("constratium_ore", () -> new ConstratiumOreBlock());
	public static final RegistryObject<Block> CONSTRATIUM_BLOCK = REGISTRY.register("constratium_block", () -> new ConstratiumBlockBlock());
	public static final RegistryObject<Block> ACTIVATED_LAMP = REGISTRY.register("activated_lamp", () -> new ActivatedLampBlock());
	public static final RegistryObject<Block> QUZAN_DOOR = REGISTRY.register("quzan_door", () -> new QuzanDoorBlock());
	public static final RegistryObject<Block> MATTER_ANTIMATTER_COMPRESSOR = REGISTRY.register("matter_antimatter_compressor", () -> new MatterAntimatterCompressorBlock());
	public static final RegistryObject<Block> ROM_PROGRAMMER = REGISTRY.register("rom_programmer", () -> new ROMProgrammerBlock());
	public static final RegistryObject<Block> SUPERCOOLED_ICE = REGISTRY.register("supercooled_ice", () -> new SupercooledIceBlock());
	public static final RegistryObject<Block> HEAT_PIPE = REGISTRY.register("heat_pipe", () -> new HeatPipeBlock());
	public static final RegistryObject<Block> PLUTONIUM_FUEL_ROD_BUNDLE = REGISTRY.register("plutonium_fuel_rod_bundle", () -> new PlutoniumFuelRodBundleBlock());
	public static final RegistryObject<Block> HEAT_PIPE_BENT = REGISTRY.register("heat_pipe_bent", () -> new HeatPipeBentBlock());
	public static final RegistryObject<Block> BREATHABLE_AIR = REGISTRY.register("breathable_air", () -> new BreathableAirBlock());
	public static final RegistryObject<Block> APARTMENT_SPAWNER = REGISTRY.register("apartment_spawner", () -> new ApartmentSpawnerBlock());
	public static final RegistryObject<Block> ROAD_SPAWNER = REGISTRY.register("road_spawner", () -> new RoadSpawnerBlock());
	public static final RegistryObject<Block> LIGHT_WATER_MODERATION_TANKS = REGISTRY.register("light_water_moderation_tanks", () -> new LightWaterModerationTanksBlock());
	public static final RegistryObject<Block> STEAM_GENERATOR = REGISTRY.register("steam_generator", () -> new SteamGeneratorBlock());
	public static final RegistryObject<Block> COPPER_CABLE = REGISTRY.register("copper_cable", () -> new CopperCableBlock());
	public static final RegistryObject<Block> RADIOISOTOPE_THERMOELECTRIC_GENERATOR = REGISTRY.register("radioisotope_thermoelectric_generator", () -> new RadioisotopeThermoelectricGeneratorBlock());
	public static final RegistryObject<Block> CRUDE_SEEBECK_GENERATOR = REGISTRY.register("crude_seebeck_generator", () -> new CrudeSeebeckGeneratorBlock());
	public static final RegistryObject<Block> AMMONICITE = REGISTRY.register("ammonicite", () -> new AmmoniciteBlock());
	public static final RegistryObject<Block> HYDROGEN_SULFIDE = REGISTRY.register("hydrogen_sulfide", () -> new HydrogenSulfideBlock());
	public static final RegistryObject<Block> SULFUR_BLOCK = REGISTRY.register("sulfur_block", () -> new SulfurBlockBlock());
	public static final RegistryObject<Block> ATMOSPHERIC_LIQUIDFIER = REGISTRY.register("atmospheric_liquidfier", () -> new AtmosphericLiquidfierBlock());
	public static final RegistryObject<Block> CHEMISTRY_WORKBENCH = REGISTRY.register("chemistry_workbench", () -> new ChemistryWorkbenchBlock());

	// Start of user code block custom blocks
	// End of user code block custom blocks
	@Mod.EventBusSubscriber(bus = Mod.EventBusSubscriber.Bus.MOD, value = Dist.CLIENT)
	public static class ClientSideHandler {
		@SubscribeEvent
		public static void blockColorLoad(RegisterColorHandlersEvent.Block event) {
			EtauosianGrainstalkBlock.blockColorLoad(event);
			ImmatureEtauosianGrainstalkBlock.blockColorLoad(event);
		}

		@SubscribeEvent
		public static void itemColorLoad(RegisterColorHandlersEvent.Item event) {
			ImmatureEtauosianGrainstalkBlock.itemColorLoad(event);
		}
	}
}
