
/*
 *	MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.far_out.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.common.extensions.IForgeMenuType;

import net.minecraft.world.inventory.MenuType;

import net.mcreator.far_out.world.inventory.ZanavosMapMenu;
import net.mcreator.far_out.world.inventory.ZPinchFusionReactorGUIMenu;
import net.mcreator.far_out.world.inventory.TuQegMapMenu;
import net.mcreator.far_out.world.inventory.TradingGUIMenu;
import net.mcreator.far_out.world.inventory.TaukuaMapMenu;
import net.mcreator.far_out.world.inventory.TableOfContentsMenu;
import net.mcreator.far_out.world.inventory.StationReadyForLaunchGUIMenu;
import net.mcreator.far_out.world.inventory.StartingLanderGUIMenu;
import net.mcreator.far_out.world.inventory.SpacecraftTrajectoriesMenu;
import net.mcreator.far_out.world.inventory.SpacecraftPropertiesMenu;
import net.mcreator.far_out.world.inventory.SpaceStationLaunchGUIMenu;
import net.mcreator.far_out.world.inventory.SpaceStationGUIMenu;
import net.mcreator.far_out.world.inventory.SpaceStationBlueprintGUIMenu;
import net.mcreator.far_out.world.inventory.SandosProxmaiMapMenu;
import net.mcreator.far_out.world.inventory.SandosMassivoMapMenu;
import net.mcreator.far_out.world.inventory.SandosMapMenu;
import net.mcreator.far_out.world.inventory.SandosEtauiMapMenu;
import net.mcreator.far_out.world.inventory.RomProgrammingStartGUIMenu;
import net.mcreator.far_out.world.inventory.RocketyPg4Menu;
import net.mcreator.far_out.world.inventory.RocketryPg9Menu;
import net.mcreator.far_out.world.inventory.RocketryPg8Menu;
import net.mcreator.far_out.world.inventory.RocketryPg7Menu;
import net.mcreator.far_out.world.inventory.RocketryPg6Menu;
import net.mcreator.far_out.world.inventory.RocketryPg5Menu;
import net.mcreator.far_out.world.inventory.RocketryPg3Menu;
import net.mcreator.far_out.world.inventory.RocketryPg2Menu;
import net.mcreator.far_out.world.inventory.RocketryPg1Menu;
import net.mcreator.far_out.world.inventory.RocketAssemblyManagerGUIMenu;
import net.mcreator.far_out.world.inventory.RejonaMapMenu;
import net.mcreator.far_out.world.inventory.RejonaGUIMenu;
import net.mcreator.far_out.world.inventory.RejonaGUIInterstellarMenu;
import net.mcreator.far_out.world.inventory.RecipesGUIMenu;
import net.mcreator.far_out.world.inventory.ReadyForLaunchGUIMenu;
import net.mcreator.far_out.world.inventory.QuaTuMapMenu;
import net.mcreator.far_out.world.inventory.OreExtractorGUIMenu;
import net.mcreator.far_out.world.inventory.OraxMapMenu;
import net.mcreator.far_out.world.inventory.OraxGUIMenu;
import net.mcreator.far_out.world.inventory.OraxGUIInterstellarMenu;
import net.mcreator.far_out.world.inventory.NuclearReactorGUIMenu;
import net.mcreator.far_out.world.inventory.MissionControlGUIMenu;
import net.mcreator.far_out.world.inventory.MethanePolymerizerRecipesMenu;
import net.mcreator.far_out.world.inventory.MethanePolymerizerGUIMenu;
import net.mcreator.far_out.world.inventory.MatterAntimatterCompressorGUIMenu;
import net.mcreator.far_out.world.inventory.MainMapMenu;
import net.mcreator.far_out.world.inventory.IntgratedCircuitFabricatorRecipesGUIMenu;
import net.mcreator.far_out.world.inventory.IntegratedCircutFabricatorRecipesMenu;
import net.mcreator.far_out.world.inventory.IntegratedCircuitFabricatorGUIMenu;
import net.mcreator.far_out.world.inventory.HydrogenFuelCellRecipesMenu;
import net.mcreator.far_out.world.inventory.HydrogenFuelCellGUIMenu;
import net.mcreator.far_out.world.inventory.HelpGUIMenu;
import net.mcreator.far_out.world.inventory.GravityChangerMenu;
import net.mcreator.far_out.world.inventory.GlobularClusterMapMenu;
import net.mcreator.far_out.world.inventory.GlobularClusterMapAfterDiscoveryMenu;
import net.mcreator.far_out.world.inventory.GeneticSequencerMenu;
import net.mcreator.far_out.world.inventory.FusionreactorguiMenu;
import net.mcreator.far_out.world.inventory.FusionReactorRecipesGUIMenu;
import net.mcreator.far_out.world.inventory.Formalonx2Menu;
import net.mcreator.far_out.world.inventory.Formalonx2InterstellarMenu;
import net.mcreator.far_out.world.inventory.Formalonx2DeltaVMenu;
import net.mcreator.far_out.world.inventory.FormalonRejonaMapMenu;
import net.mcreator.far_out.world.inventory.FormalonOraxMapMenu;
import net.mcreator.far_out.world.inventory.FormalonMapMenu;
import net.mcreator.far_out.world.inventory.FormalonMainMenu;
import net.mcreator.far_out.world.inventory.FormalonMainInterstellarMenu;
import net.mcreator.far_out.world.inventory.FormalonMainDeltaVMenu;
import net.mcreator.far_out.world.inventory.ElectrolyzerGUIRecipesMenu;
import net.mcreator.far_out.world.inventory.ElectrolyzerGUIMenu;
import net.mcreator.far_out.world.inventory.DesktopComputerGUIMenu;
import net.mcreator.far_out.world.inventory.DesigningWorkbenchGUIMenu;
import net.mcreator.far_out.world.inventory.CrystalDriveGUIMenu;
import net.mcreator.far_out.world.inventory.CoalGasificationReactorRecipesMenu;
import net.mcreator.far_out.world.inventory.CoalGasificationReactorGUIMenu;
import net.mcreator.far_out.world.inventory.ChemistryWorkbenchGUIMenu;
import net.mcreator.far_out.world.inventory.CargoSSTOBlueprintGUIMenu;
import net.mcreator.far_out.world.inventory.CalculatorGUIMenu;
import net.mcreator.far_out.world.inventory.BlankPageMenu;
import net.mcreator.far_out.world.inventory.BeamInjectorGUIMenu;
import net.mcreator.far_out.world.inventory.AvionicsProgrammingGUIMenu;
import net.mcreator.far_out.world.inventory.AtmosphericLiquidiferGUIMenu;
import net.mcreator.far_out.world.inventory.AmmeterGUIMenu;
import net.mcreator.far_out.FaroutMod;

public class FaroutModMenus {
	public static final DeferredRegister<MenuType<?>> REGISTRY = DeferredRegister.create(ForgeRegistries.MENU_TYPES, FaroutMod.MODID);
	public static final RegistryObject<MenuType<FusionreactorguiMenu>> FUSIONREACTORGUI = REGISTRY.register("fusionreactorgui", () -> IForgeMenuType.create(FusionreactorguiMenu::new));
	public static final RegistryObject<MenuType<ElectrolyzerGUIMenu>> ELECTROLYZER_GUI = REGISTRY.register("electrolyzer_gui", () -> IForgeMenuType.create(ElectrolyzerGUIMenu::new));
	public static final RegistryObject<MenuType<GeneticSequencerMenu>> GENETIC_SEQUENCER = REGISTRY.register("genetic_sequencer", () -> IForgeMenuType.create(GeneticSequencerMenu::new));
	public static final RegistryObject<MenuType<StartingLanderGUIMenu>> STARTING_LANDER_GUI = REGISTRY.register("starting_lander_gui", () -> IForgeMenuType.create(StartingLanderGUIMenu::new));
	public static final RegistryObject<MenuType<CrystalDriveGUIMenu>> CRYSTAL_DRIVE_GUI = REGISTRY.register("crystal_drive_gui", () -> IForgeMenuType.create(CrystalDriveGUIMenu::new));
	public static final RegistryObject<MenuType<IntegratedCircuitFabricatorGUIMenu>> INTEGRATED_CIRCUIT_FABRICATOR_GUI = REGISTRY.register("integrated_circuit_fabricator_gui", () -> IForgeMenuType.create(IntegratedCircuitFabricatorGUIMenu::new));
	public static final RegistryObject<MenuType<BeamInjectorGUIMenu>> BEAM_INJECTOR_GUI = REGISTRY.register("beam_injector_gui", () -> IForgeMenuType.create(BeamInjectorGUIMenu::new));
	public static final RegistryObject<MenuType<SandosMapMenu>> SANDOS_MAP = REGISTRY.register("sandos_map", () -> IForgeMenuType.create(SandosMapMenu::new));
	public static final RegistryObject<MenuType<ZPinchFusionReactorGUIMenu>> Z_PINCH_FUSION_REACTOR_GUI = REGISTRY.register("z_pinch_fusion_reactor_gui", () -> IForgeMenuType.create(ZPinchFusionReactorGUIMenu::new));
	public static final RegistryObject<MenuType<RejonaMapMenu>> REJONA_MAP = REGISTRY.register("rejona_map", () -> IForgeMenuType.create(RejonaMapMenu::new));
	public static final RegistryObject<MenuType<OraxMapMenu>> ORAX_MAP = REGISTRY.register("orax_map", () -> IForgeMenuType.create(OraxMapMenu::new));
	public static final RegistryObject<MenuType<MainMapMenu>> MAIN_MAP = REGISTRY.register("main_map", () -> IForgeMenuType.create(MainMapMenu::new));
	public static final RegistryObject<MenuType<DesktopComputerGUIMenu>> DESKTOP_COMPUTER_GUI = REGISTRY.register("desktop_computer_gui", () -> IForgeMenuType.create(DesktopComputerGUIMenu::new));
	public static final RegistryObject<MenuType<OreExtractorGUIMenu>> ORE_EXTRACTOR_GUI = REGISTRY.register("ore_extractor_gui", () -> IForgeMenuType.create(OreExtractorGUIMenu::new));
	public static final RegistryObject<MenuType<GravityChangerMenu>> GRAVITY_CHANGER = REGISTRY.register("gravity_changer", () -> IForgeMenuType.create(GravityChangerMenu::new));
	public static final RegistryObject<MenuType<MissionControlGUIMenu>> MISSION_CONTROL_GUI = REGISTRY.register("mission_control_gui", () -> IForgeMenuType.create(MissionControlGUIMenu::new));
	public static final RegistryObject<MenuType<HydrogenFuelCellGUIMenu>> HYDROGEN_FUEL_CELL_GUI = REGISTRY.register("hydrogen_fuel_cell_gui", () -> IForgeMenuType.create(HydrogenFuelCellGUIMenu::new));
	public static final RegistryObject<MenuType<AmmeterGUIMenu>> AMMETER_GUI = REGISTRY.register("ammeter_gui", () -> IForgeMenuType.create(AmmeterGUIMenu::new));
	public static final RegistryObject<MenuType<DesigningWorkbenchGUIMenu>> DESIGNING_WORKBENCH_GUI = REGISTRY.register("designing_workbench_gui", () -> IForgeMenuType.create(DesigningWorkbenchGUIMenu::new));
	public static final RegistryObject<MenuType<RocketAssemblyManagerGUIMenu>> ROCKET_ASSEMBLY_MANAGER_GUI = REGISTRY.register("rocket_assembly_manager_gui", () -> IForgeMenuType.create(RocketAssemblyManagerGUIMenu::new));
	public static final RegistryObject<MenuType<ReadyForLaunchGUIMenu>> READY_FOR_LAUNCH_GUI = REGISTRY.register("ready_for_launch_gui", () -> IForgeMenuType.create(ReadyForLaunchGUIMenu::new));
	public static final RegistryObject<MenuType<CoalGasificationReactorGUIMenu>> COAL_GASIFICATION_REACTOR_GUI = REGISTRY.register("coal_gasification_reactor_gui", () -> IForgeMenuType.create(CoalGasificationReactorGUIMenu::new));
	public static final RegistryObject<MenuType<SpaceStationBlueprintGUIMenu>> SPACE_STATION_BLUEPRINT_GUI = REGISTRY.register("space_station_blueprint_gui", () -> IForgeMenuType.create(SpaceStationBlueprintGUIMenu::new));
	public static final RegistryObject<MenuType<CargoSSTOBlueprintGUIMenu>> CARGO_SSTO_BLUEPRINT_GUI = REGISTRY.register("cargo_ssto_blueprint_gui", () -> IForgeMenuType.create(CargoSSTOBlueprintGUIMenu::new));
	public static final RegistryObject<MenuType<StationReadyForLaunchGUIMenu>> STATION_READY_FOR_LAUNCH_GUI = REGISTRY.register("station_ready_for_launch_gui", () -> IForgeMenuType.create(StationReadyForLaunchGUIMenu::new));
	public static final RegistryObject<MenuType<SpaceStationGUIMenu>> SPACE_STATION_GUI = REGISTRY.register("space_station_gui", () -> IForgeMenuType.create(SpaceStationGUIMenu::new));
	public static final RegistryObject<MenuType<SpaceStationLaunchGUIMenu>> SPACE_STATION_LAUNCH_GUI = REGISTRY.register("space_station_launch_gui", () -> IForgeMenuType.create(SpaceStationLaunchGUIMenu::new));
	public static final RegistryObject<MenuType<TableOfContentsMenu>> TABLE_OF_CONTENTS = REGISTRY.register("table_of_contents", () -> IForgeMenuType.create(TableOfContentsMenu::new));
	public static final RegistryObject<MenuType<RocketryPg1Menu>> ROCKETRY_PG_1 = REGISTRY.register("rocketry_pg_1", () -> IForgeMenuType.create(RocketryPg1Menu::new));
	public static final RegistryObject<MenuType<FormalonMainMenu>> FORMALON_MAIN = REGISTRY.register("formalon_main", () -> IForgeMenuType.create(FormalonMainMenu::new));
	public static final RegistryObject<MenuType<RejonaGUIMenu>> REJONA_GUI = REGISTRY.register("rejona_gui", () -> IForgeMenuType.create(RejonaGUIMenu::new));
	public static final RegistryObject<MenuType<Formalonx2Menu>> FORMALONX_2 = REGISTRY.register("formalonx_2", () -> IForgeMenuType.create(Formalonx2Menu::new));
	public static final RegistryObject<MenuType<FormalonMainInterstellarMenu>> FORMALON_MAIN_INTERSTELLAR = REGISTRY.register("formalon_main_interstellar", () -> IForgeMenuType.create(FormalonMainInterstellarMenu::new));
	public static final RegistryObject<MenuType<Formalonx2InterstellarMenu>> FORMALONX_2_INTERSTELLAR = REGISTRY.register("formalonx_2_interstellar", () -> IForgeMenuType.create(Formalonx2InterstellarMenu::new));
	public static final RegistryObject<MenuType<RejonaGUIInterstellarMenu>> REJONA_GUI_INTERSTELLAR = REGISTRY.register("rejona_gui_interstellar", () -> IForgeMenuType.create(RejonaGUIInterstellarMenu::new));
	public static final RegistryObject<MenuType<OraxGUIMenu>> ORAX_GUI = REGISTRY.register("orax_gui", () -> IForgeMenuType.create(OraxGUIMenu::new));
	public static final RegistryObject<MenuType<OraxGUIInterstellarMenu>> ORAX_GUI_INTERSTELLAR = REGISTRY.register("orax_gui_interstellar", () -> IForgeMenuType.create(OraxGUIInterstellarMenu::new));
	public static final RegistryObject<MenuType<RocketryPg3Menu>> ROCKETRY_PG_3 = REGISTRY.register("rocketry_pg_3", () -> IForgeMenuType.create(RocketryPg3Menu::new));
	public static final RegistryObject<MenuType<RocketyPg4Menu>> ROCKETY_PG_4 = REGISTRY.register("rockety_pg_4", () -> IForgeMenuType.create(RocketyPg4Menu::new));
	public static final RegistryObject<MenuType<RocketryPg5Menu>> ROCKETRY_PG_5 = REGISTRY.register("rocketry_pg_5", () -> IForgeMenuType.create(RocketryPg5Menu::new));
	public static final RegistryObject<MenuType<MethanePolymerizerGUIMenu>> METHANE_POLYMERIZER_GUI = REGISTRY.register("methane_polymerizer_gui", () -> IForgeMenuType.create(MethanePolymerizerGUIMenu::new));
	public static final RegistryObject<MenuType<RocketryPg2Menu>> ROCKETRY_PG_2 = REGISTRY.register("rocketry_pg_2", () -> IForgeMenuType.create(RocketryPg2Menu::new));
	public static final RegistryObject<MenuType<RocketryPg6Menu>> ROCKETRY_PG_6 = REGISTRY.register("rocketry_pg_6", () -> IForgeMenuType.create(RocketryPg6Menu::new));
	public static final RegistryObject<MenuType<RocketryPg7Menu>> ROCKETRY_PG_7 = REGISTRY.register("rocketry_pg_7", () -> IForgeMenuType.create(RocketryPg7Menu::new));
	public static final RegistryObject<MenuType<BlankPageMenu>> BLANK_PAGE = REGISTRY.register("blank_page", () -> IForgeMenuType.create(BlankPageMenu::new));
	public static final RegistryObject<MenuType<RocketryPg8Menu>> ROCKETRY_PG_8 = REGISTRY.register("rocketry_pg_8", () -> IForgeMenuType.create(RocketryPg8Menu::new));
	public static final RegistryObject<MenuType<ElectrolyzerGUIRecipesMenu>> ELECTROLYZER_GUI_RECIPES = REGISTRY.register("electrolyzer_gui_recipes", () -> IForgeMenuType.create(ElectrolyzerGUIRecipesMenu::new));
	public static final RegistryObject<MenuType<FormalonMainDeltaVMenu>> FORMALON_MAIN_DELTA_V = REGISTRY.register("formalon_main_delta_v", () -> IForgeMenuType.create(FormalonMainDeltaVMenu::new));
	public static final RegistryObject<MenuType<Formalonx2DeltaVMenu>> FORMALONX_2_DELTA_V = REGISTRY.register("formalonx_2_delta_v", () -> IForgeMenuType.create(Formalonx2DeltaVMenu::new));
	public static final RegistryObject<MenuType<NuclearReactorGUIMenu>> NUCLEAR_REACTOR_GUI = REGISTRY.register("nuclear_reactor_gui", () -> IForgeMenuType.create(NuclearReactorGUIMenu::new));
	public static final RegistryObject<MenuType<RocketryPg9Menu>> ROCKETRY_PG_9 = REGISTRY.register("rocketry_pg_9", () -> IForgeMenuType.create(RocketryPg9Menu::new));
	public static final RegistryObject<MenuType<FusionReactorRecipesGUIMenu>> FUSION_REACTOR_RECIPES_GUI = REGISTRY.register("fusion_reactor_recipes_gui", () -> IForgeMenuType.create(FusionReactorRecipesGUIMenu::new));
	public static final RegistryObject<MenuType<IntgratedCircuitFabricatorRecipesGUIMenu>> INTGRATED_CIRCUIT_FABRICATOR_RECIPES_GUI = REGISTRY.register("intgrated_circuit_fabricator_recipes_gui",
			() -> IForgeMenuType.create(IntgratedCircuitFabricatorRecipesGUIMenu::new));
	public static final RegistryObject<MenuType<HydrogenFuelCellRecipesMenu>> HYDROGEN_FUEL_CELL_RECIPES = REGISTRY.register("hydrogen_fuel_cell_recipes", () -> IForgeMenuType.create(HydrogenFuelCellRecipesMenu::new));
	public static final RegistryObject<MenuType<CoalGasificationReactorRecipesMenu>> COAL_GASIFICATION_REACTOR_RECIPES = REGISTRY.register("coal_gasification_reactor_recipes", () -> IForgeMenuType.create(CoalGasificationReactorRecipesMenu::new));
	public static final RegistryObject<MenuType<MethanePolymerizerRecipesMenu>> METHANE_POLYMERIZER_RECIPES = REGISTRY.register("methane_polymerizer_recipes", () -> IForgeMenuType.create(MethanePolymerizerRecipesMenu::new));
	public static final RegistryObject<MenuType<IntegratedCircutFabricatorRecipesMenu>> INTEGRATED_CIRCUT_FABRICATOR_RECIPES = REGISTRY.register("integrated_circut_fabricator_recipes",
			() -> IForgeMenuType.create(IntegratedCircutFabricatorRecipesMenu::new));
	public static final RegistryObject<MenuType<RecipesGUIMenu>> RECIPES_GUI = REGISTRY.register("recipes_gui", () -> IForgeMenuType.create(RecipesGUIMenu::new));
	public static final RegistryObject<MenuType<SandosEtauiMapMenu>> SANDOS_ETAUI_MAP = REGISTRY.register("sandos_etaui_map", () -> IForgeMenuType.create(SandosEtauiMapMenu::new));
	public static final RegistryObject<MenuType<SandosProxmaiMapMenu>> SANDOS_PROXMAI_MAP = REGISTRY.register("sandos_proxmai_map", () -> IForgeMenuType.create(SandosProxmaiMapMenu::new));
	public static final RegistryObject<MenuType<SandosMassivoMapMenu>> SANDOS_MASSIVO_MAP = REGISTRY.register("sandos_massivo_map", () -> IForgeMenuType.create(SandosMassivoMapMenu::new));
	public static final RegistryObject<MenuType<FormalonMapMenu>> FORMALON_MAP = REGISTRY.register("formalon_map", () -> IForgeMenuType.create(FormalonMapMenu::new));
	public static final RegistryObject<MenuType<FormalonOraxMapMenu>> FORMALON_ORAX_MAP = REGISTRY.register("formalon_orax_map", () -> IForgeMenuType.create(FormalonOraxMapMenu::new));
	public static final RegistryObject<MenuType<FormalonRejonaMapMenu>> FORMALON_REJONA_MAP = REGISTRY.register("formalon_rejona_map", () -> IForgeMenuType.create(FormalonRejonaMapMenu::new));
	public static final RegistryObject<MenuType<GlobularClusterMapMenu>> GLOBULAR_CLUSTER_MAP = REGISTRY.register("globular_cluster_map", () -> IForgeMenuType.create(GlobularClusterMapMenu::new));
	public static final RegistryObject<MenuType<TuQegMapMenu>> TU_QEG_MAP = REGISTRY.register("tu_qeg_map", () -> IForgeMenuType.create(TuQegMapMenu::new));
	public static final RegistryObject<MenuType<ZanavosMapMenu>> ZANAVOS_MAP = REGISTRY.register("zanavos_map", () -> IForgeMenuType.create(ZanavosMapMenu::new));
	public static final RegistryObject<MenuType<QuaTuMapMenu>> QUA_TU_MAP = REGISTRY.register("qua_tu_map", () -> IForgeMenuType.create(QuaTuMapMenu::new));
	public static final RegistryObject<MenuType<TaukuaMapMenu>> TAUKUA_MAP = REGISTRY.register("taukua_map", () -> IForgeMenuType.create(TaukuaMapMenu::new));
	public static final RegistryObject<MenuType<SpacecraftPropertiesMenu>> SPACECRAFT_PROPERTIES = REGISTRY.register("spacecraft_properties", () -> IForgeMenuType.create(SpacecraftPropertiesMenu::new));
	public static final RegistryObject<MenuType<SpacecraftTrajectoriesMenu>> SPACECRAFT_TRAJECTORIES = REGISTRY.register("spacecraft_trajectories", () -> IForgeMenuType.create(SpacecraftTrajectoriesMenu::new));
	public static final RegistryObject<MenuType<TradingGUIMenu>> TRADING_GUI = REGISTRY.register("trading_gui", () -> IForgeMenuType.create(TradingGUIMenu::new));
	public static final RegistryObject<MenuType<MatterAntimatterCompressorGUIMenu>> MATTER_ANTIMATTER_COMPRESSOR_GUI = REGISTRY.register("matter_antimatter_compressor_gui", () -> IForgeMenuType.create(MatterAntimatterCompressorGUIMenu::new));
	public static final RegistryObject<MenuType<RomProgrammingStartGUIMenu>> ROM_PROGRAMMING_START_GUI = REGISTRY.register("rom_programming_start_gui", () -> IForgeMenuType.create(RomProgrammingStartGUIMenu::new));
	public static final RegistryObject<MenuType<AvionicsProgrammingGUIMenu>> AVIONICS_PROGRAMMING_GUI = REGISTRY.register("avionics_programming_gui", () -> IForgeMenuType.create(AvionicsProgrammingGUIMenu::new));
	public static final RegistryObject<MenuType<CalculatorGUIMenu>> CALCULATOR_GUI = REGISTRY.register("calculator_gui", () -> IForgeMenuType.create(CalculatorGUIMenu::new));
	public static final RegistryObject<MenuType<GlobularClusterMapAfterDiscoveryMenu>> GLOBULAR_CLUSTER_MAP_AFTER_DISCOVERY = REGISTRY.register("globular_cluster_map_after_discovery",
			() -> IForgeMenuType.create(GlobularClusterMapAfterDiscoveryMenu::new));
	public static final RegistryObject<MenuType<AtmosphericLiquidiferGUIMenu>> ATMOSPHERIC_LIQUIDIFER_GUI = REGISTRY.register("atmospheric_liquidifer_gui", () -> IForgeMenuType.create(AtmosphericLiquidiferGUIMenu::new));
	public static final RegistryObject<MenuType<HelpGUIMenu>> HELP_GUI = REGISTRY.register("help_gui", () -> IForgeMenuType.create(HelpGUIMenu::new));
	public static final RegistryObject<MenuType<ChemistryWorkbenchGUIMenu>> CHEMISTRY_WORKBENCH_GUI = REGISTRY.register("chemistry_workbench_gui", () -> IForgeMenuType.create(ChemistryWorkbenchGUIMenu::new));
}
