
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.far_out.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.common.ForgeSpawnEggItem;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.DoubleHighBlockItem;
import net.minecraft.world.item.BlockItem;

import net.mcreator.far_out.item.ZirconItem;
import net.mcreator.far_out.item.XenonItem;
import net.mcreator.far_out.item.WrenchItem;
import net.mcreator.far_out.item.VodkaItem;
import net.mcreator.far_out.item.UraniumCarbideItem;
import net.mcreator.far_out.item.UnetchedSiliconWaferItem;
import net.mcreator.far_out.item.TritiumItem;
import net.mcreator.far_out.item.TrihassianCurrencyItem;
import net.mcreator.far_out.item.TransconiumSwordItem;
import net.mcreator.far_out.item.TheFaroutGuideItem;
import net.mcreator.far_out.item.TelescopeBlueprintItem;
import net.mcreator.far_out.item.SulfuricAcidItem;
import net.mcreator.far_out.item.SulfurDustItem;
import net.mcreator.far_out.item.SulfurDioxideItem;
import net.mcreator.far_out.item.SteamItem;
import net.mcreator.far_out.item.SpodumeneItem;
import net.mcreator.far_out.item.SpaceshipBlueprintItem;
import net.mcreator.far_out.item.SpaceSuitItem;
import net.mcreator.far_out.item.SolidAntimatterPenningTrapItem;
import net.mcreator.far_out.item.SodiumIngotItem;
import net.mcreator.far_out.item.SodiumHydroxideItem;
import net.mcreator.far_out.item.SodiumAluminateItem;
import net.mcreator.far_out.item.SmallAtmosphericLanderItem;
import net.mcreator.far_out.item.SiliconDustItem;
import net.mcreator.far_out.item.SandosStarmapItem;
import net.mcreator.far_out.item.SandosArenaItem;
import net.mcreator.far_out.item.SaltwaterItem;
import net.mcreator.far_out.item.SaltDustItem;
import net.mcreator.far_out.item.RocketryIconItem;
import net.mcreator.far_out.item.RelayItem;
import net.mcreator.far_out.item.ReactorIconItem;
import net.mcreator.far_out.item.RailgunItem;
import net.mcreator.far_out.item.RadioLocatorForwardItem;
import net.mcreator.far_out.item.PyriteNuggetItem;
import net.mcreator.far_out.item.PulsarEmblemItem;
import net.mcreator.far_out.item.PrimeNumbersEmblemItem;
import net.mcreator.far_out.item.Potassium_nitrateDustItem;
import net.mcreator.far_out.item.PolyethyleneItem;
import net.mcreator.far_out.item.PlutoniumCarbideItem;
import net.mcreator.far_out.item.PipeItem;
import net.mcreator.far_out.item.PhotovoltaicWaferPhotomaskItem;
import net.mcreator.far_out.item.PhotovoltaicWaferItem;
import net.mcreator.far_out.item.PenningTrapItem;
import net.mcreator.far_out.item.OxygenBottleItem;
import net.mcreator.far_out.item.OceanusEmblemItem;
import net.mcreator.far_out.item.NuclearPistonItem;
import net.mcreator.far_out.item.NitrogenItem;
import net.mcreator.far_out.item.MotorItem;
import net.mcreator.far_out.item.MethaneItem;
import net.mcreator.far_out.item.MediumFrequencyIntegratedCircuitPhotomaskItem;
import net.mcreator.far_out.item.MediumFrequencyIntegratedCircuitItem;
import net.mcreator.far_out.item.MediumCapacityMemoryPhotomaskItem;
import net.mcreator.far_out.item.MediumCapacityMemoryItem;
import net.mcreator.far_out.item.MagmaItem;
import net.mcreator.far_out.item.LowFrequencyIntegratedCircuitItem;
import net.mcreator.far_out.item.LowCapacityMemoryItem;
import net.mcreator.far_out.item.LonsdaleiteSwordItem;
import net.mcreator.far_out.item.LonsdaleiteShovelItem;
import net.mcreator.far_out.item.LonsdaleitePickaxeItem;
import net.mcreator.far_out.item.LonsdaleiteItem;
import net.mcreator.far_out.item.LonsdaleiteHoeItem;
import net.mcreator.far_out.item.LonsdaleiteAxeItem;
import net.mcreator.far_out.item.LonsdaleiteArmorItem;
import net.mcreator.far_out.item.LiquidSulfurDioxideItem;
import net.mcreator.far_out.item.LiquidMethaneItem;
import net.mcreator.far_out.item.LiquidAmmoniaItem;
import net.mcreator.far_out.item.LightbulbEmblemItem;
import net.mcreator.far_out.item.LaserItem;
import net.mcreator.far_out.item.IronplateItem;
import net.mcreator.far_out.item.IronWheelItem;
import net.mcreator.far_out.item.IronRodItem;
import net.mcreator.far_out.item.IronReinforcedSpaceSuitItem;
import net.mcreator.far_out.item.IronPentacarbonylItem;
import net.mcreator.far_out.item.InertialNavigationSystemItem;
import net.mcreator.far_out.item.InertialNavUnitPhotomaskItem;
import net.mcreator.far_out.item.ImpureCryogenicFluidsItem;
import net.mcreator.far_out.item.HydrogenSulfideItem;
import net.mcreator.far_out.item.HydrogenItem;
import net.mcreator.far_out.item.HexuraningotItem;
import net.mcreator.far_out.item.HexuranSwordItem;
import net.mcreator.far_out.item.HexuranShovelItem;
import net.mcreator.far_out.item.HexuranPickaxeItem;
import net.mcreator.far_out.item.HexuranHoeItem;
import net.mcreator.far_out.item.HexuranAxeItem;
import net.mcreator.far_out.item.HeliumItem;
import net.mcreator.far_out.item.Helium3Item;
import net.mcreator.far_out.item.HafniumCarbonitrideIngotItem;
import net.mcreator.far_out.item.GreenOilItem;
import net.mcreator.far_out.item.GraphiterodItem;
import net.mcreator.far_out.item.GraphiteIngotItem;
import net.mcreator.far_out.item.GoInterstellaremblemItem;
import net.mcreator.far_out.item.GalacticCoreTrackerItem;
import net.mcreator.far_out.item.FusionEmblemItem;
import net.mcreator.far_out.item.FusionChamberItem;
import net.mcreator.far_out.item.FissionEmblemItem;
import net.mcreator.far_out.item.EtauosianGrainStalkSeedsItem;
import net.mcreator.far_out.item.EmergencyRationsItem;
import net.mcreator.far_out.item.ElectroMagnetItem;
import net.mcreator.far_out.item.DriedChlorellaItem;
import net.mcreator.far_out.item.DiamondReinfocedSpaceSuitItem;
import net.mcreator.far_out.item.DeuteriumItem;
import net.mcreator.far_out.item.DepletedUraniumItem;
import net.mcreator.far_out.item.DepletedPlutoniumItem;
import net.mcreator.far_out.item.CopperWireItem;
import net.mcreator.far_out.item.ConstratiumItem;
import net.mcreator.far_out.item.CoffiniteItem;
import net.mcreator.far_out.item.ChlorineItem;
import net.mcreator.far_out.item.ChlorellaCultureItem;
import net.mcreator.far_out.item.CathodeRayTubeMonitorItem;
import net.mcreator.far_out.item.CarbonDioxideItem;
import net.mcreator.far_out.item.CapacitorItem;
import net.mcreator.far_out.item.CalculatorItem;
import net.mcreator.far_out.item.BulletItemItem;
import net.mcreator.far_out.item.BoronIngotItem;
import net.mcreator.far_out.item.BoricAcidItem;
import net.mcreator.far_out.item.BoraxItem;
import net.mcreator.far_out.item.BoratedSteelIngotItem;
import net.mcreator.far_out.item.BlackHoleComputerItem;
import net.mcreator.far_out.item.BauxiteNuggetItem;
import net.mcreator.far_out.item.BasicSolarCellItem;
import net.mcreator.far_out.item.AvionicsGuidanceSystemItem;
import net.mcreator.far_out.item.AutomaticRifleItem;
import net.mcreator.far_out.item.AqueousAmmoniaItem;
import net.mcreator.far_out.item.AntimatterCollectorBlueprintItem;
import net.mcreator.far_out.item.AmmoniaItem;
import net.mcreator.far_out.item.AmmeterItem;
import net.mcreator.far_out.item.AluminiumIngotItem;
import net.mcreator.far_out.item.AluminiumHydroxideItem;
import net.mcreator.far_out.item.AlgaeBarItem;
import net.mcreator.far_out.item.AirtightFabricItem;
import net.mcreator.far_out.item.AetherianConquerorEmblemItem;
import net.mcreator.far_out.block.display.StirlingEngineDisplayItem;
import net.mcreator.far_out.block.display.RocketAssemblerDisplayItem;
import net.mcreator.far_out.FaroutMod;

public class FaroutModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, FaroutMod.MODID);
	public static final RegistryObject<Item> SPACE_SUIT_HELMET = REGISTRY.register("space_suit_helmet", () -> new SpaceSuitItem.Helmet());
	public static final RegistryObject<Item> SPACE_SUIT_CHESTPLATE = REGISTRY.register("space_suit_chestplate", () -> new SpaceSuitItem.Chestplate());
	public static final RegistryObject<Item> SPACE_SUIT_LEGGINGS = REGISTRY.register("space_suit_leggings", () -> new SpaceSuitItem.Leggings());
	public static final RegistryObject<Item> GRAPHITEROD = REGISTRY.register("graphiterod", () -> new GraphiterodItem());
	public static final RegistryObject<Item> DEPLETED_URANIUM = REGISTRY.register("depleted_uranium", () -> new DepletedUraniumItem());
	public static final RegistryObject<Item> TOKAMAKFUSIONREACTOR = block(FaroutModBlocks.TOKAMAKFUSIONREACTOR);
	public static final RegistryObject<Item> BORON_INGOT = REGISTRY.register("boron_ingot", () -> new BoronIngotItem());
	public static final RegistryObject<Item> DEUTERIUM = REGISTRY.register("deuterium", () -> new DeuteriumItem());
	public static final RegistryObject<Item> HELIUM_3 = REGISTRY.register("helium_3", () -> new Helium3Item());
	public static final RegistryObject<Item> TRITIUM = REGISTRY.register("tritium", () -> new TritiumItem());
	public static final RegistryObject<Item> HELIUM = REGISTRY.register("helium", () -> new HeliumItem());
	public static final RegistryObject<Item> IRONPLATE = REGISTRY.register("ironplate", () -> new IronplateItem());
	public static final RegistryObject<Item> HEXURANINGOT = REGISTRY.register("hexuraningot", () -> new HexuraningotItem());
	public static final RegistryObject<Item> HEXURAN_PICKAXE = REGISTRY.register("hexuran_pickaxe", () -> new HexuranPickaxeItem());
	public static final RegistryObject<Item> HEXURAN_AXE = REGISTRY.register("hexuran_axe", () -> new HexuranAxeItem());
	public static final RegistryObject<Item> HEXURAN_SWORD = REGISTRY.register("hexuran_sword", () -> new HexuranSwordItem());
	public static final RegistryObject<Item> HEXURAN_SHOVEL = REGISTRY.register("hexuran_shovel", () -> new HexuranShovelItem());
	public static final RegistryObject<Item> HEXURAN_HOE = REGISTRY.register("hexuran_hoe", () -> new HexuranHoeItem());
	public static final RegistryObject<Item> SULFUR_DUST = REGISTRY.register("sulfur_dust", () -> new SulfurDustItem());
	public static final RegistryObject<Item> POTASSIUM_NITRATE_DUST = REGISTRY.register("potassium_nitrate_dust", () -> new Potassium_nitrateDustItem());
	public static final RegistryObject<Item> MOTOR = REGISTRY.register("motor", () -> new MotorItem());
	public static final RegistryObject<Item> PIPE = REGISTRY.register("pipe", () -> new PipeItem());
	public static final RegistryObject<Item> CARDBOARDBOX = block(FaroutModBlocks.CARDBOARDBOX);
	public static final RegistryObject<Item> CHACOA = block(FaroutModBlocks.CHACOA);
	public static final RegistryObject<Item> CHACOAVINES = block(FaroutModBlocks.CHACOAVINES);
	public static final RegistryObject<Item> DESKTOP_COMPUTER = block(FaroutModBlocks.DESKTOP_COMPUTER);
	public static final RegistryObject<Item> GRAPHITE_INGOT = REGISTRY.register("graphite_ingot", () -> new GraphiteIngotItem());
	public static final RegistryObject<Item> GRAPHITE_ORE = block(FaroutModBlocks.GRAPHITE_ORE);
	public static final RegistryObject<Item> COPPER_WIRE = REGISTRY.register("copper_wire", () -> new CopperWireItem());
	public static final RegistryObject<Item> ELECTRO_MAGNET = REGISTRY.register("electro_magnet", () -> new ElectroMagnetItem());
	public static final RegistryObject<Item> SILICON_DUST = REGISTRY.register("silicon_dust", () -> new SiliconDustItem());
	public static final RegistryObject<Item> ELECTROLYZER = block(FaroutModBlocks.ELECTROLYZER);
	public static final RegistryObject<Item> VODKA = REGISTRY.register("vodka", () -> new VodkaItem());
	public static final RegistryObject<Item> SALTWATER_BUCKET = REGISTRY.register("saltwater_bucket", () -> new SaltwaterItem());
	public static final RegistryObject<Item> ALIEN_REEDS = block(FaroutModBlocks.ALIEN_REEDS);
	public static final RegistryObject<Item> BIO_PLASTIC_WINDOW = block(FaroutModBlocks.BIO_PLASTIC_WINDOW);
	public static final RegistryObject<Item> SODIUM_HYDROXIDE = REGISTRY.register("sodium_hydroxide", () -> new SodiumHydroxideItem());
	public static final RegistryObject<Item> BORATED_STEEL_INGOT = REGISTRY.register("borated_steel_ingot", () -> new BoratedSteelIngotItem());
	public static final RegistryObject<Item> WRENCH = REGISTRY.register("wrench", () -> new WrenchItem());
	public static final RegistryObject<Item> LOW_FREQUENCY_INTEGRATED_CIRCUIT = REGISTRY.register("low_frequency_integrated_circuit", () -> new LowFrequencyIntegratedCircuitItem());
	public static final RegistryObject<Item> MEDIUM_FREQUENCY_INTEGRATED_CIRCUIT = REGISTRY.register("medium_frequency_integrated_circuit", () -> new MediumFrequencyIntegratedCircuitItem());
	public static final RegistryObject<Item> INTEGRATED_CIRCUIT_FABRICATOR = block(FaroutModBlocks.INTEGRATED_CIRCUIT_FABRICATOR);
	public static final RegistryObject<Item> ALUMINIUM_INGOT = REGISTRY.register("aluminium_ingot", () -> new AluminiumIngotItem());
	public static final RegistryObject<Item> BAUXITE = block(FaroutModBlocks.BAUXITE);
	public static final RegistryObject<Item> HYDROGEN = REGISTRY.register("hydrogen", () -> new HydrogenItem());
	public static final RegistryObject<Item> SULFURIC_ACID_BUCKET = REGISTRY.register("sulfuric_acid_bucket", () -> new SulfuricAcidItem());
	public static final RegistryObject<Item> CHEMOSYNTHETIC_NODULES = block(FaroutModBlocks.CHEMOSYNTHETIC_NODULES);
	public static final RegistryObject<Item> CRYSTALINE_EXOSKELETON = block(FaroutModBlocks.CRYSTALINE_EXOSKELETON);
	public static final RegistryObject<Item> GREEN_OIL_BUCKET = REGISTRY.register("green_oil_bucket", () -> new GreenOilItem());
	public static final RegistryObject<Item> ASPHALT = block(FaroutModBlocks.ASPHALT);
	public static final RegistryObject<Item> LIQUID_AMMONIA_BUCKET = REGISTRY.register("liquid_ammonia_bucket", () -> new LiquidAmmoniaItem());
	public static final RegistryObject<Item> EMERGENCY_RATIONS = REGISTRY.register("emergency_rations", () -> new EmergencyRationsItem());
	public static final RegistryObject<Item> CARGO_POD = block(FaroutModBlocks.CARGO_POD);
	public static final RegistryObject<Item> UNETCHED_SILICON_WAFER = REGISTRY.register("unetched_silicon_wafer", () -> new UnetchedSiliconWaferItem());
	public static final RegistryObject<Item> MEDIUM_CAPACITY_MEMORY = REGISTRY.register("medium_capacity_memory", () -> new MediumCapacityMemoryItem());
	public static final RegistryObject<Item> LOW_CAPACITY_MEMORY = REGISTRY.register("low_capacity_memory", () -> new LowCapacityMemoryItem());
	public static final RegistryObject<Item> AIRTIGHT_HABITAT_WALL = block(FaroutModBlocks.AIRTIGHT_HABITAT_WALL);
	public static final RegistryObject<Item> SMALL_ATMOSPHERIC_LANDER = REGISTRY.register("small_atmospheric_lander", () -> new SmallAtmosphericLanderItem());
	public static final RegistryObject<Item> Z_PINCH_FUSION_REACTOR = block(FaroutModBlocks.Z_PINCH_FUSION_REACTOR);
	public static final RegistryObject<Item> FUSION_CHAMBER = REGISTRY.register("fusion_chamber", () -> new FusionChamberItem());
	public static final RegistryObject<Item> COFFINITE = REGISTRY.register("coffinite", () -> new CoffiniteItem());
	public static final RegistryObject<Item> COFFINITE_ORE = block(FaroutModBlocks.COFFINITE_ORE);
	public static final RegistryObject<Item> OXYGEN_BOTTLE = REGISTRY.register("oxygen_bottle", () -> new OxygenBottleItem());
	public static final RegistryObject<Item> SPODUMENE = REGISTRY.register("spodumene", () -> new SpodumeneItem());
	public static final RegistryObject<Item> SPODUMENE_ORE = block(FaroutModBlocks.SPODUMENE_ORE);
	public static final RegistryObject<Item> INERTIAL_NAVIGATION_SYSTEM = REGISTRY.register("inertial_navigation_system", () -> new InertialNavigationSystemItem());
	public static final RegistryObject<Item> LASER = REGISTRY.register("laser", () -> new LaserItem());
	public static final RegistryObject<Item> GALACTIC_CORE_TRACKER = REGISTRY.register("galactic_core_tracker", () -> new GalacticCoreTrackerItem());
	public static final RegistryObject<Item> LUMIBLOSSOM_WOOD = block(FaroutModBlocks.LUMIBLOSSOM_WOOD);
	public static final RegistryObject<Item> LUMIBLOSSOM_LOG = block(FaroutModBlocks.LUMIBLOSSOM_LOG);
	public static final RegistryObject<Item> LUMIBLOSSOM_PLANKS = block(FaroutModBlocks.LUMIBLOSSOM_PLANKS);
	public static final RegistryObject<Item> LUMIBLOSSOM_STAIRS = block(FaroutModBlocks.LUMIBLOSSOM_STAIRS);
	public static final RegistryObject<Item> LUMIBLOSSOM_SLAB = block(FaroutModBlocks.LUMIBLOSSOM_SLAB);
	public static final RegistryObject<Item> LUMIBLOSSOM_FENCE = block(FaroutModBlocks.LUMIBLOSSOM_FENCE);
	public static final RegistryObject<Item> LUMIBLOSSOM_FENCE_GATE = block(FaroutModBlocks.LUMIBLOSSOM_FENCE_GATE);
	public static final RegistryObject<Item> LUMIBLOSSOM_PRESSURE_PLATE = block(FaroutModBlocks.LUMIBLOSSOM_PRESSURE_PLATE);
	public static final RegistryObject<Item> LUMIBLOSSOM_BUTTON = block(FaroutModBlocks.LUMIBLOSSOM_BUTTON);
	public static final RegistryObject<Item> QUARTZ_ORE = block(FaroutModBlocks.QUARTZ_ORE);
	public static final RegistryObject<Item> PHOTOVOLTAIC_WAFER = REGISTRY.register("photovoltaic_wafer", () -> new PhotovoltaicWaferItem());
	public static final RegistryObject<Item> THE_FAROUT_GUIDE = REGISTRY.register("the_farout_guide", () -> new TheFaroutGuideItem());
	public static final RegistryObject<Item> SOLAR_VINES_CAP = block(FaroutModBlocks.SOLAR_VINES_CAP);
	public static final RegistryObject<Item> SOLAR_VINES = block(FaroutModBlocks.SOLAR_VINES);
	public static final RegistryObject<Item> RED_TORCHER = block(FaroutModBlocks.RED_TORCHER);
	public static final RegistryObject<Item> YELLOW_TORCHER = block(FaroutModBlocks.YELLOW_TORCHER);
	public static final RegistryObject<Item> BLUE_TORCHER = block(FaroutModBlocks.BLUE_TORCHER);
	public static final RegistryObject<Item> CHLORELLA_CULTURE_BUCKET = REGISTRY.register("chlorella_culture_bucket", () -> new ChlorellaCultureItem());
	public static final RegistryObject<Item> DRIED_CHLORELLA = REGISTRY.register("dried_chlorella", () -> new DriedChlorellaItem());
	public static final RegistryObject<Item> ALGAE_BAR = REGISTRY.register("algae_bar", () -> new AlgaeBarItem());
	public static final RegistryObject<Item> OCEANUS_EMBLEM = REGISTRY.register("oceanus_emblem", () -> new OceanusEmblemItem());
	public static final RegistryObject<Item> ANCIENT_SEDIMENT = block(FaroutModBlocks.ANCIENT_SEDIMENT);
	public static final RegistryObject<Item> SALT_DUST = REGISTRY.register("salt_dust", () -> new SaltDustItem());
	public static final RegistryObject<Item> SALT_BLOCK = block(FaroutModBlocks.SALT_BLOCK);
	public static final RegistryObject<Item> LIQUID_SULFUR_DIOXIDE_BUCKET = REGISTRY.register("liquid_sulfur_dioxide_bucket", () -> new LiquidSulfurDioxideItem());
	public static final RegistryObject<Item> LUMIBLOSSOM_LEAVES = block(FaroutModBlocks.LUMIBLOSSOM_LEAVES);
	public static final RegistryObject<Item> RUST = block(FaroutModBlocks.RUST);
	public static final RegistryObject<Item> CRUSHED_QUARTZ = block(FaroutModBlocks.CRUSHED_QUARTZ);
	public static final RegistryObject<Item> URANIUM_CARBIDE = REGISTRY.register("uranium_carbide", () -> new UraniumCarbideItem());
	public static final RegistryObject<Item> AQUEOUS_AMMONIA_BUCKET = REGISTRY.register("aqueous_ammonia_bucket", () -> new AqueousAmmoniaItem());
	public static final RegistryObject<Item> PLUTONIUM_CARBIDE = REGISTRY.register("plutonium_carbide", () -> new PlutoniumCarbideItem());
	public static final RegistryObject<Item> HYDROGEN_FUEL_CELL = block(FaroutModBlocks.HYDROGEN_FUEL_CELL);
	public static final RegistryObject<Item> BASALTIC_DIRT = block(FaroutModBlocks.BASALTIC_DIRT);
	public static final RegistryObject<Item> ETAUOSIAN_GRAINSTALK = block(FaroutModBlocks.ETAUOSIAN_GRAINSTALK);
	public static final RegistryObject<Item> ETAUOSIAN_GRAIN_STALK_SEEDS = REGISTRY.register("etauosian_grain_stalk_seeds", () -> new EtauosianGrainStalkSeedsItem());
	public static final RegistryObject<Item> STIRLING_ENGINE = REGISTRY.register(FaroutModBlocks.STIRLING_ENGINE.getId().getPath(), () -> new StirlingEngineDisplayItem(FaroutModBlocks.STIRLING_ENGINE.get(), new Item.Properties()));
	public static final RegistryObject<Item> IMMATURE_ETAUOSIAN_GRAINSTALK = block(FaroutModBlocks.IMMATURE_ETAUOSIAN_GRAINSTALK);
	public static final RegistryObject<Item> RELAY = REGISTRY.register("relay", () -> new RelayItem());
	public static final RegistryObject<Item> CAPACITOR = REGISTRY.register("capacitor", () -> new CapacitorItem());
	public static final RegistryObject<Item> AMMETER = REGISTRY.register("ammeter", () -> new AmmeterItem());
	public static final RegistryObject<Item> IRON_ROD = REGISTRY.register("iron_rod", () -> new IronRodItem());
	public static final RegistryObject<Item> IRON_WHEEL = REGISTRY.register("iron_wheel", () -> new IronWheelItem());
	public static final RegistryObject<Item> MUSNIUS_TREE_TRUNK = block(FaroutModBlocks.MUSNIUS_TREE_TRUNK);
	public static final RegistryObject<Item> MUSNIUS_WOOD = block(FaroutModBlocks.MUSNIUS_WOOD);
	public static final RegistryObject<Item> MUSNIUS_STAIRS = block(FaroutModBlocks.MUSNIUS_STAIRS);
	public static final RegistryObject<Item> MUSNIUS_SLAB = block(FaroutModBlocks.MUSNIUS_SLAB);
	public static final RegistryObject<Item> MUSNIUS_FENCE = block(FaroutModBlocks.MUSNIUS_FENCE);
	public static final RegistryObject<Item> MUSNIUS_FENCE_GATE = block(FaroutModBlocks.MUSNIUS_FENCE_GATE);
	public static final RegistryObject<Item> MUSNIUS_PRESSURE_PLATE = block(FaroutModBlocks.MUSNIUS_PRESSURE_PLATE);
	public static final RegistryObject<Item> MUSNIUS_BUTTON = block(FaroutModBlocks.MUSNIUS_BUTTON);
	public static final RegistryObject<Item> MUSNIUS_PLANKS = block(FaroutModBlocks.MUSNIUS_PLANKS);
	public static final RegistryObject<Item> MUSNIUS_LEAVES = block(FaroutModBlocks.MUSNIUS_LEAVES);
	public static final RegistryObject<Item> MUSNIUS_SAPLING = block(FaroutModBlocks.MUSNIUS_SAPLING);
	public static final RegistryObject<Item> REACTOR_ICON = REGISTRY.register("reactor_icon", () -> new ReactorIconItem());
	public static final RegistryObject<Item> DESIGNING_WORKBENCH = block(FaroutModBlocks.DESIGNING_WORKBENCH);
	public static final RegistryObject<Item> SPACESHIP_BLUEPRINT = REGISTRY.register("spaceship_blueprint", () -> new SpaceshipBlueprintItem());
	public static final RegistryObject<Item> LAUNCHPAD_TILES = block(FaroutModBlocks.LAUNCHPAD_TILES);
	public static final RegistryObject<Item> ROCKETRY_ICON = REGISTRY.register("rocketry_icon", () -> new RocketryIconItem());
	public static final RegistryObject<Item> ROCKET_ASSEMBLY_MANAGER = block(FaroutModBlocks.ROCKET_ASSEMBLY_MANAGER);
	public static final RegistryObject<Item> ROCKET_ASSEMBLER = REGISTRY.register(FaroutModBlocks.ROCKET_ASSEMBLER.getId().getPath(), () -> new RocketAssemblerDisplayItem(FaroutModBlocks.ROCKET_ASSEMBLER.get(), new Item.Properties()));
	public static final RegistryObject<Item> LIQUID_METHANE_BUCKET = REGISTRY.register("liquid_methane_bucket", () -> new LiquidMethaneItem());
	public static final RegistryObject<Item> XENON = REGISTRY.register("xenon", () -> new XenonItem());
	public static final RegistryObject<Item> HAFNIUM_CARBONITRIDE_INGOT = REGISTRY.register("hafnium_carbonitride_ingot", () -> new HafniumCarbonitrideIngotItem());
	public static final RegistryObject<Item> SOLID_ANTIMATTER_PENNING_TRAP = REGISTRY.register("solid_antimatter_penning_trap", () -> new SolidAntimatterPenningTrapItem());
	public static final RegistryObject<Item> PENNING_TRAP = REGISTRY.register("penning_trap", () -> new PenningTrapItem());
	public static final RegistryObject<Item> STRALAKITE = block(FaroutModBlocks.STRALAKITE);
	public static final RegistryObject<Item> SOLAR_PANELS = block(FaroutModBlocks.SOLAR_PANELS);
	public static final RegistryObject<Item> METHANE = REGISTRY.register("methane", () -> new MethaneItem());
	public static final RegistryObject<Item> CARGO_SSTO_SPAWN_EGG = REGISTRY.register("cargo_ssto_spawn_egg", () -> new ForgeSpawnEggItem(FaroutModEntities.CARGO_SSTO, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> KEMPAT_WOOD = block(FaroutModBlocks.KEMPAT_WOOD);
	public static final RegistryObject<Item> KEMPAT_LOG = block(FaroutModBlocks.KEMPAT_LOG);
	public static final RegistryObject<Item> KEMPAT_PLANKS = block(FaroutModBlocks.KEMPAT_PLANKS);
	public static final RegistryObject<Item> KEMPAT_LEAVES = block(FaroutModBlocks.KEMPAT_LEAVES);
	public static final RegistryObject<Item> KEMPAT_STAIRS = block(FaroutModBlocks.KEMPAT_STAIRS);
	public static final RegistryObject<Item> KEMPAT_SLAB = block(FaroutModBlocks.KEMPAT_SLAB);
	public static final RegistryObject<Item> KEMPAT_FENCE = block(FaroutModBlocks.KEMPAT_FENCE);
	public static final RegistryObject<Item> KEMPAT_FENCE_GATE = block(FaroutModBlocks.KEMPAT_FENCE_GATE);
	public static final RegistryObject<Item> KEMPAT_PRESSURE_PLATE = block(FaroutModBlocks.KEMPAT_PRESSURE_PLATE);
	public static final RegistryObject<Item> KEMPAT_BUTTON = block(FaroutModBlocks.KEMPAT_BUTTON);
	public static final RegistryObject<Item> CATHODE_RAY_TUBE_MONITOR = REGISTRY.register("cathode_ray_tube_monitor", () -> new CathodeRayTubeMonitorItem());
	public static final RegistryObject<Item> GRAPHITE_ROD_ASSEMBLY = block(FaroutModBlocks.GRAPHITE_ROD_ASSEMBLY);
	public static final RegistryObject<Item> LIGHTBULB_EMBLEM = REGISTRY.register("lightbulb_emblem", () -> new LightbulbEmblemItem());
	public static final RegistryObject<Item> POLYETHYLENE = REGISTRY.register("polyethylene", () -> new PolyethyleneItem());
	public static final RegistryObject<Item> BASIC_SOLAR_CELL = REGISTRY.register("basic_solar_cell", () -> new BasicSolarCellItem());
	public static final RegistryObject<Item> BAUXITE_NUGGET = REGISTRY.register("bauxite_nugget", () -> new BauxiteNuggetItem());
	public static final RegistryObject<Item> CHLORINATED_EARTH = block(FaroutModBlocks.CHLORINATED_EARTH);
	public static final RegistryObject<Item> BORAX_ORE = block(FaroutModBlocks.BORAX_ORE);
	public static final RegistryObject<Item> BORAX = REGISTRY.register("borax", () -> new BoraxItem());
	public static final RegistryObject<Item> BORIC_ACID = REGISTRY.register("boric_acid", () -> new BoricAcidItem());
	public static final RegistryObject<Item> UNACTIVATED_LAMP = block(FaroutModBlocks.UNACTIVATED_LAMP);
	public static final RegistryObject<Item> TRANSCONIUM_SWORD = REGISTRY.register("transconium_sword", () -> new TransconiumSwordItem());
	public static final RegistryObject<Item> SODIUM_INGOT = REGISTRY.register("sodium_ingot", () -> new SodiumIngotItem());
	public static final RegistryObject<Item> PYRITE = block(FaroutModBlocks.PYRITE);
	public static final RegistryObject<Item> PYRITE_NUGGET = REGISTRY.register("pyrite_nugget", () -> new PyriteNuggetItem());
	public static final RegistryObject<Item> SANDOS_ARENA = REGISTRY.register("sandos_arena", () -> new SandosArenaItem());
	public static final RegistryObject<Item> GRAPHITE_ROD_ASSEMBLY_PLUTONIUM = block(FaroutModBlocks.GRAPHITE_ROD_ASSEMBLY_PLUTONIUM);
	public static final RegistryObject<Item> GRAPHITE_ROD_ASSEMBLY_URANIUM = block(FaroutModBlocks.GRAPHITE_ROD_ASSEMBLY_URANIUM);
	public static final RegistryObject<Item> ZIRCON = REGISTRY.register("zircon", () -> new ZirconItem());
	public static final RegistryObject<Item> ZIRCON_ORE = block(FaroutModBlocks.ZIRCON_ORE);
	public static final RegistryObject<Item> PURPLEGRASS = block(FaroutModBlocks.PURPLEGRASS);
	public static final RegistryObject<Item> SUBSPACE_CATALYST = block(FaroutModBlocks.SUBSPACE_CATALYST);
	public static final RegistryObject<Item> IRON_REINFORCED_SPACE_SUIT_HELMET = REGISTRY.register("iron_reinforced_space_suit_helmet", () -> new IronReinforcedSpaceSuitItem.Helmet());
	public static final RegistryObject<Item> IRON_REINFORCED_SPACE_SUIT_CHESTPLATE = REGISTRY.register("iron_reinforced_space_suit_chestplate", () -> new IronReinforcedSpaceSuitItem.Chestplate());
	public static final RegistryObject<Item> IRON_REINFORCED_SPACE_SUIT_LEGGINGS = REGISTRY.register("iron_reinforced_space_suit_leggings", () -> new IronReinforcedSpaceSuitItem.Leggings());
	public static final RegistryObject<Item> DIAMOND_REINFOCED_SPACE_SUIT_HELMET = REGISTRY.register("diamond_reinfoced_space_suit_helmet", () -> new DiamondReinfocedSpaceSuitItem.Helmet());
	public static final RegistryObject<Item> DIAMOND_REINFOCED_SPACE_SUIT_CHESTPLATE = REGISTRY.register("diamond_reinfoced_space_suit_chestplate", () -> new DiamondReinfocedSpaceSuitItem.Chestplate());
	public static final RegistryObject<Item> DIAMOND_REINFOCED_SPACE_SUIT_LEGGINGS = REGISTRY.register("diamond_reinfoced_space_suit_leggings", () -> new DiamondReinfocedSpaceSuitItem.Leggings());
	public static final RegistryObject<Item> MEDIUM_FREQUENCY_INTEGRATED_CIRCUIT_PHOTOMASK = REGISTRY.register("medium_frequency_integrated_circuit_photomask", () -> new MediumFrequencyIntegratedCircuitPhotomaskItem());
	public static final RegistryObject<Item> MEDIUM_CAPACITY_MEMORY_PHOTOMASK = REGISTRY.register("medium_capacity_memory_photomask", () -> new MediumCapacityMemoryPhotomaskItem());
	public static final RegistryObject<Item> PHOTOVOLTAIC_WAFER_PHOTOMASK = REGISTRY.register("photovoltaic_wafer_photomask", () -> new PhotovoltaicWaferPhotomaskItem());
	public static final RegistryObject<Item> INERTIAL_NAV_UNIT_PHOTOMASK = REGISTRY.register("inertial_nav_unit_photomask", () -> new InertialNavUnitPhotomaskItem());
	public static final RegistryObject<Item> RADIO_LOCATOR_FORWARD = REGISTRY.register("radio_locator_forward", () -> new RadioLocatorForwardItem());
	public static final RegistryObject<Item> METHANE_POLYMERIZER = block(FaroutModBlocks.METHANE_POLYMERIZER);
	public static final RegistryObject<Item> QUZAN_WOOD = block(FaroutModBlocks.QUZAN_WOOD);
	public static final RegistryObject<Item> QUZAN_LOG = block(FaroutModBlocks.QUZAN_LOG);
	public static final RegistryObject<Item> QUZAN_PLANKS = block(FaroutModBlocks.QUZAN_PLANKS);
	public static final RegistryObject<Item> QUZAN_LEAVES = block(FaroutModBlocks.QUZAN_LEAVES);
	public static final RegistryObject<Item> QUZAN_STAIRS = block(FaroutModBlocks.QUZAN_STAIRS);
	public static final RegistryObject<Item> QUZAN_SLAB = block(FaroutModBlocks.QUZAN_SLAB);
	public static final RegistryObject<Item> QUZAN_FENCE = block(FaroutModBlocks.QUZAN_FENCE);
	public static final RegistryObject<Item> QUZAN_FENCE_GATE = block(FaroutModBlocks.QUZAN_FENCE_GATE);
	public static final RegistryObject<Item> QUZAN_PRESSURE_PLATE = block(FaroutModBlocks.QUZAN_PRESSURE_PLATE);
	public static final RegistryObject<Item> QUZAN_BUTTON = block(FaroutModBlocks.QUZAN_BUTTON);
	public static final RegistryObject<Item> LONSDALEITE = REGISTRY.register("lonsdaleite", () -> new LonsdaleiteItem());
	public static final RegistryObject<Item> LONSDALEITE_ORE = block(FaroutModBlocks.LONSDALEITE_ORE);
	public static final RegistryObject<Item> LONSDALEITE_BLOCK = block(FaroutModBlocks.LONSDALEITE_BLOCK);
	public static final RegistryObject<Item> LONSDALEITE_PICKAXE = REGISTRY.register("lonsdaleite_pickaxe", () -> new LonsdaleitePickaxeItem());
	public static final RegistryObject<Item> LONSDALEITE_AXE = REGISTRY.register("lonsdaleite_axe", () -> new LonsdaleiteAxeItem());
	public static final RegistryObject<Item> LONSDALEITE_SWORD = REGISTRY.register("lonsdaleite_sword", () -> new LonsdaleiteSwordItem());
	public static final RegistryObject<Item> LONSDALEITE_SHOVEL = REGISTRY.register("lonsdaleite_shovel", () -> new LonsdaleiteShovelItem());
	public static final RegistryObject<Item> LONSDALEITE_HOE = REGISTRY.register("lonsdaleite_hoe", () -> new LonsdaleiteHoeItem());
	public static final RegistryObject<Item> LONSDALEITE_ARMOR_HELMET = REGISTRY.register("lonsdaleite_armor_helmet", () -> new LonsdaleiteArmorItem.Helmet());
	public static final RegistryObject<Item> LONSDALEITE_ARMOR_CHESTPLATE = REGISTRY.register("lonsdaleite_armor_chestplate", () -> new LonsdaleiteArmorItem.Chestplate());
	public static final RegistryObject<Item> LONSDALEITE_ARMOR_LEGGINGS = REGISTRY.register("lonsdaleite_armor_leggings", () -> new LonsdaleiteArmorItem.Leggings());
	public static final RegistryObject<Item> LONSDALEITE_ARMOR_BOOTS = REGISTRY.register("lonsdaleite_armor_boots", () -> new LonsdaleiteArmorItem.Boots());
	public static final RegistryObject<Item> AIRTIGHT_FABRIC = REGISTRY.register("airtight_fabric", () -> new AirtightFabricItem());
	public static final RegistryObject<Item> NUCLEAR_PISTON = REGISTRY.register("nuclear_piston", () -> new NuclearPistonItem());
	public static final RegistryObject<Item> AETHERIAN_CONQUEROR_EMBLEM = REGISTRY.register("aetherian_conqueror_emblem", () -> new AetherianConquerorEmblemItem());
	public static final RegistryObject<Item> DEPLETED_PLUTONIUM = REGISTRY.register("depleted_plutonium", () -> new DepletedPlutoniumItem());
	public static final RegistryObject<Item> NUCLEAR_REACTOR = block(FaroutModBlocks.NUCLEAR_REACTOR);
	public static final RegistryObject<Item> KEMPAT_SAPLING = block(FaroutModBlocks.KEMPAT_SAPLING);
	public static final RegistryObject<Item> OXYFION_WOOD = block(FaroutModBlocks.OXYFION_WOOD);
	public static final RegistryObject<Item> OXYFION_LOG = block(FaroutModBlocks.OXYFION_LOG);
	public static final RegistryObject<Item> OXYFION_PLANKS = block(FaroutModBlocks.OXYFION_PLANKS);
	public static final RegistryObject<Item> OXYFION_LEAVES = block(FaroutModBlocks.OXYFION_LEAVES);
	public static final RegistryObject<Item> OXYFION_STAIRS = block(FaroutModBlocks.OXYFION_STAIRS);
	public static final RegistryObject<Item> OXYFION_SLAB = block(FaroutModBlocks.OXYFION_SLAB);
	public static final RegistryObject<Item> OXYFION_FENCE = block(FaroutModBlocks.OXYFION_FENCE);
	public static final RegistryObject<Item> OXYFION_FENCE_GATE = block(FaroutModBlocks.OXYFION_FENCE_GATE);
	public static final RegistryObject<Item> OXYFION_PRESSURE_PLATE = block(FaroutModBlocks.OXYFION_PRESSURE_PLATE);
	public static final RegistryObject<Item> OXYFION_BUTTON = block(FaroutModBlocks.OXYFION_BUTTON);
	public static final RegistryObject<Item> IRON_PENTACARBONYL_BUCKET = REGISTRY.register("iron_pentacarbonyl_bucket", () -> new IronPentacarbonylItem());
	public static final RegistryObject<Item> URANISTONE = block(FaroutModBlocks.URANISTONE);
	public static final RegistryObject<Item> MAGMA_BUCKET = REGISTRY.register("magma_bucket", () -> new MagmaItem());
	public static final RegistryObject<Item> KERANON_WOOD = block(FaroutModBlocks.KERANON_WOOD);
	public static final RegistryObject<Item> KERANON_LOG = block(FaroutModBlocks.KERANON_LOG);
	public static final RegistryObject<Item> KERANON_PLANKS = block(FaroutModBlocks.KERANON_PLANKS);
	public static final RegistryObject<Item> KERANON_LEAVES = block(FaroutModBlocks.KERANON_LEAVES);
	public static final RegistryObject<Item> KERANON_STAIRS = block(FaroutModBlocks.KERANON_STAIRS);
	public static final RegistryObject<Item> KERANON_SLAB = block(FaroutModBlocks.KERANON_SLAB);
	public static final RegistryObject<Item> KERANON_FENCE = block(FaroutModBlocks.KERANON_FENCE);
	public static final RegistryObject<Item> KERANON_FENCE_GATE = block(FaroutModBlocks.KERANON_FENCE_GATE);
	public static final RegistryObject<Item> KERANON_PRESSURE_PLATE = block(FaroutModBlocks.KERANON_PRESSURE_PLATE);
	public static final RegistryObject<Item> KERANON_BUTTON = block(FaroutModBlocks.KERANON_BUTTON);
	public static final RegistryObject<Item> RAILGUN = REGISTRY.register("railgun", () -> new RailgunItem());
	public static final RegistryObject<Item> SANDOS_STARMAP = REGISTRY.register("sandos_starmap", () -> new SandosStarmapItem());
	public static final RegistryObject<Item> HYPERSTABLE_ALLOY = block(FaroutModBlocks.HYPERSTABLE_ALLOY);
	public static final RegistryObject<Item> HYPERSTABLE_ALLOY_STAIRS = block(FaroutModBlocks.HYPERSTABLE_ALLOY_STAIRS);
	public static final RegistryObject<Item> ASTRAL_DRAGON_SPAWN_EGG = REGISTRY.register("astral_dragon_spawn_egg", () -> new ForgeSpawnEggItem(FaroutModEntities.ASTRAL_DRAGON, -843759, -37632, new Item.Properties()));
	public static final RegistryObject<Item> KARVON_WARPSHIP_SPAWN_EGG = REGISTRY.register("karvon_warpship_spawn_egg", () -> new ForgeSpawnEggItem(FaroutModEntities.KARVON_WARPSHIP, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> SENTINEL_SPAWN_EGG = REGISTRY.register("sentinel_spawn_egg", () -> new ForgeSpawnEggItem(FaroutModEntities.SENTINEL, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> FUSION_EMBLEM = REGISTRY.register("fusion_emblem", () -> new FusionEmblemItem());
	public static final RegistryObject<Item> GO_INTERSTELLAREMBLEM = REGISTRY.register("go_interstellaremblem", () -> new GoInterstellaremblemItem());
	public static final RegistryObject<Item> RED_ALGAE = block(FaroutModBlocks.RED_ALGAE);
	public static final RegistryObject<Item> CONSTRATIUM = REGISTRY.register("constratium", () -> new ConstratiumItem());
	public static final RegistryObject<Item> CONSTRATIUM_ORE = block(FaroutModBlocks.CONSTRATIUM_ORE);
	public static final RegistryObject<Item> CONSTRATIUM_BLOCK = block(FaroutModBlocks.CONSTRATIUM_BLOCK);
	public static final RegistryObject<Item> TRIHASSIAN_SPAWN_EGG = REGISTRY.register("trihassian_spawn_egg", () -> new ForgeSpawnEggItem(FaroutModEntities.TRIHASSIAN, -3407668, -10092442, new Item.Properties()));
	public static final RegistryObject<Item> TRIHASSIAN_CURRENCY = REGISTRY.register("trihassian_currency", () -> new TrihassianCurrencyItem());
	public static final RegistryObject<Item> BULLET_ITEM = REGISTRY.register("bullet_item", () -> new BulletItemItem());
	public static final RegistryObject<Item> TRIHASSIAN_SOLDER_SPAWN_EGG = REGISTRY.register("trihassian_solder_spawn_egg", () -> new ForgeSpawnEggItem(FaroutModEntities.TRIHASSIAN_SOLDER, -3407668, -14323441, new Item.Properties()));
	public static final RegistryObject<Item> ACTIVATED_LAMP = block(FaroutModBlocks.ACTIVATED_LAMP);
	public static final RegistryObject<Item> QUZAN_DOOR = doubleBlock(FaroutModBlocks.QUZAN_DOOR);
	public static final RegistryObject<Item> BLACK_HOLE_COMPUTER = REGISTRY.register("black_hole_computer", () -> new BlackHoleComputerItem());
	public static final RegistryObject<Item> MATTER_ANTIMATTER_COMPRESSOR = block(FaroutModBlocks.MATTER_ANTIMATTER_COMPRESSOR);
	public static final RegistryObject<Item> ANTIMATTER_COLLECTOR_BLUEPRINT = REGISTRY.register("antimatter_collector_blueprint", () -> new AntimatterCollectorBlueprintItem());
	public static final RegistryObject<Item> AVIONICS_GUIDANCE_SYSTEM = REGISTRY.register("avionics_guidance_system", () -> new AvionicsGuidanceSystemItem());
	public static final RegistryObject<Item> ROM_PROGRAMMER = block(FaroutModBlocks.ROM_PROGRAMMER);
	public static final RegistryObject<Item> AUTOMATIC_RIFLE = REGISTRY.register("automatic_rifle", () -> new AutomaticRifleItem());
	public static final RegistryObject<Item> CALCULATOR = REGISTRY.register("calculator", () -> new CalculatorItem());
	public static final RegistryObject<Item> SUPERCOOLED_ICE = block(FaroutModBlocks.SUPERCOOLED_ICE);
	public static final RegistryObject<Item> HEAT_PIPE = block(FaroutModBlocks.HEAT_PIPE);
	public static final RegistryObject<Item> PLUTONIUM_FUEL_ROD_BUNDLE = block(FaroutModBlocks.PLUTONIUM_FUEL_ROD_BUNDLE);
	public static final RegistryObject<Item> HEAT_PIPE_BENT = block(FaroutModBlocks.HEAT_PIPE_BENT);
	public static final RegistryObject<Item> BREATHABLE_AIR = block(FaroutModBlocks.BREATHABLE_AIR);
	public static final RegistryObject<Item> APARTMENT_SPAWNER = block(FaroutModBlocks.APARTMENT_SPAWNER);
	public static final RegistryObject<Item> ROAD_SPAWNER = block(FaroutModBlocks.ROAD_SPAWNER);
	public static final RegistryObject<Item> PRIME_NUMBERS_EMBLEM = REGISTRY.register("prime_numbers_emblem", () -> new PrimeNumbersEmblemItem());
	public static final RegistryObject<Item> PULSAR_EMBLEM = REGISTRY.register("pulsar_emblem", () -> new PulsarEmblemItem());
	public static final RegistryObject<Item> TELESCOPE_BLUEPRINT = REGISTRY.register("telescope_blueprint", () -> new TelescopeBlueprintItem());
	public static final RegistryObject<Item> LIGHT_WATER_MODERATION_TANKS = block(FaroutModBlocks.LIGHT_WATER_MODERATION_TANKS);
	public static final RegistryObject<Item> STEAM_GENERATOR = block(FaroutModBlocks.STEAM_GENERATOR);
	public static final RegistryObject<Item> COPPER_CABLE = block(FaroutModBlocks.COPPER_CABLE);
	public static final RegistryObject<Item> RADIOISOTOPE_THERMOELECTRIC_GENERATOR = block(FaroutModBlocks.RADIOISOTOPE_THERMOELECTRIC_GENERATOR);
	public static final RegistryObject<Item> CRUDE_SEEBECK_GENERATOR = block(FaroutModBlocks.CRUDE_SEEBECK_GENERATOR);
	public static final RegistryObject<Item> AMMONICITE = block(FaroutModBlocks.AMMONICITE);
	public static final RegistryObject<Item> HYDROGEN_SULFIDE_BUCKET = REGISTRY.register("hydrogen_sulfide_bucket", () -> new HydrogenSulfideItem());
	public static final RegistryObject<Item> SULFUR_BLOCK = block(FaroutModBlocks.SULFUR_BLOCK);
	public static final RegistryObject<Item> HAPOLITE_SPAWN_EGG = REGISTRY.register("hapolite_spawn_egg", () -> new ForgeSpawnEggItem(FaroutModEntities.HAPOLITE, -9542334, -13083603, new Item.Properties()));
	public static final RegistryObject<Item> CARBON_DIOXIDE = REGISTRY.register("carbon_dioxide", () -> new CarbonDioxideItem());
	public static final RegistryObject<Item> ATMOSPHERIC_LIQUIDFIER = block(FaroutModBlocks.ATMOSPHERIC_LIQUIDFIER);
	public static final RegistryObject<Item> IMPURE_CRYOGENIC_FLUIDS = REGISTRY.register("impure_cryogenic_fluids", () -> new ImpureCryogenicFluidsItem());
	public static final RegistryObject<Item> NITROGEN = REGISTRY.register("nitrogen", () -> new NitrogenItem());
	public static final RegistryObject<Item> CHLORINE = REGISTRY.register("chlorine", () -> new ChlorineItem());
	public static final RegistryObject<Item> AMMONIA = REGISTRY.register("ammonia", () -> new AmmoniaItem());
	public static final RegistryObject<Item> SULFUR_DIOXIDE = REGISTRY.register("sulfur_dioxide", () -> new SulfurDioxideItem());
	public static final RegistryObject<Item> CHEMISTRY_WORKBENCH = block(FaroutModBlocks.CHEMISTRY_WORKBENCH);
	public static final RegistryObject<Item> STEAM = REGISTRY.register("steam", () -> new SteamItem());
	public static final RegistryObject<Item> SODIUM_ALUMINATE = REGISTRY.register("sodium_aluminate", () -> new SodiumAluminateItem());
	public static final RegistryObject<Item> ALUMINIUM_HYDROXIDE = REGISTRY.register("aluminium_hydroxide", () -> new AluminiumHydroxideItem());
	public static final RegistryObject<Item> FISSION_EMBLEM = REGISTRY.register("fission_emblem", () -> new FissionEmblemItem());

	// Start of user code block custom items
	// End of user code block custom items
	private static RegistryObject<Item> block(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties()));
	}

	private static RegistryObject<Item> doubleBlock(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new DoubleHighBlockItem(block.get(), new Item.Properties()));
	}
}
